# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Tests for dbt contract to Bronze vocabulary synchronization."""

from __future__ import annotations

from pathlib import Path

import yaml
from rdflib import Graph, URIRef
from rdflib.namespace import RDF

from kairos_ontology.core.dbt_contract_sync import (
    KAIROS_BRONZE,
    KAIROS_DBT,
    sync_dbt_contracts,
)
from kairos_ontology.core.projections.medallion_dbt_projector import _parse_bronze


def _make_hub(tmp_path: Path) -> tuple[Path, Path]:
    hub = tmp_path / "hub"
    models = hub / "integration" / "transforms" / "dbt" / "models"
    models.mkdir(parents=True)
    (models / "int_orders.sql").write_text("select 1\n", encoding="utf-8")
    properties = models / "int_orders.yml"
    properties.write_text(
        yaml.safe_dump(
            {
                "version": 2,
                "models": [
                    {
                        "name": "int_orders",
                        "description": "Conformed orders.",
                        "config": {
                            "materialized": "table",
                            "contract": {"enforced": True},
                        },
                        "meta": {
                            "kairos": {
                                "target_class": "https://example.com/ont#Order",
                                "virtual_source_iri": "https://example.com/source#orders",
                                "grain": "one row per order",
                                "supported_adapters": ["fabric", "databricks"],
                                "natural_key": ["order_id"],
                                "required_packages": [],
                                "required_macros": [],
                            }
                        },
                        "columns": [
                            {
                                "name": "order_id",
                                "description": "Order identifier.",
                                "data_type": "string",
                            },
                            {"name": "amount", "data_type": "decimal(18,2)"},
                        ],
                    }
                ],
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    return hub, properties


def test_writes_bronze_compatible_graph_with_stable_iris(tmp_path: Path) -> None:
    hub, _ = _make_hub(tmp_path)
    report = sync_dbt_contracts(hub)

    assert report.written_count == 1
    item = report.items[0]
    text = item.output_path.read_text(encoding="utf-8")
    assert "DD-072" in text
    assert "Generated by kairos-ontology-toolkit" in text

    graph = Graph().parse(item.output_path, format="turtle")
    table = URIRef("https://example.com/source#orders")
    column = URIRef("https://example.com/source#orders/order_id")
    assert (table, RDF.type, KAIROS_BRONZE.SourceTable) in graph
    assert (column, RDF.type, KAIROS_BRONZE.SourceColumn) in graph
    assert (table, KAIROS_DBT.sourceKind, None) in graph

    parsed = _parse_bronze(hub / "integration" / "sources")
    assert parsed[0]["tables"][0]["name"] == "int_orders"
    assert {col["name"] for col in parsed[0]["tables"][0]["columns"]} == {
        "order_id",
        "amount",
    }


def test_semantically_equal_graph_is_not_rewritten(tmp_path: Path) -> None:
    hub, _ = _make_hub(tmp_path)
    first = sync_dbt_contracts(hub)
    output = first.items[0].output_path
    graph = Graph().parse(output, format="turtle")
    alternate = "# Different provenance timestamp\n" + graph.serialize(format="turtle")
    output.write_text(alternate, encoding="utf-8")

    second = sync_dbt_contracts(hub)

    assert second.items[0].state == "unchanged"
    assert second.written_count == 0
    assert output.read_text(encoding="utf-8") == alternate


def test_check_reports_missing_and_stale_without_writing(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    missing = sync_dbt_contracts(hub, check=True)
    output = missing.items[0].output_path
    assert missing.has_drift
    assert missing.items[0].action == "would_create"
    assert not output.exists()

    sync_dbt_contracts(hub)
    original = output.read_text(encoding="utf-8")
    document = yaml.safe_load(properties.read_text(encoding="utf-8"))
    document["models"][0]["columns"].append({"name": "status", "data_type": "string"})
    properties.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")

    stale = sync_dbt_contracts(hub, check=True)
    assert stale.items[0].state == "stale"
    assert stale.items[0].action == "would_update"
    assert output.read_text(encoding="utf-8") == original

    updated = sync_dbt_contracts(hub)
    assert updated.items[0].action == "updated"
    assert "status" in {
        str(value) for value in Graph().parse(output).objects(None, KAIROS_BRONZE.columnName)
    }


def test_missing_or_empty_transforms_are_successful_noop(tmp_path: Path) -> None:
    hub = tmp_path / "hub"
    hub.mkdir()
    absent = sync_dbt_contracts(hub)
    assert absent.items == ()
    assert not absent.sources_dir.exists()

    (hub / "integration" / "transforms" / "dbt" / "models").mkdir(parents=True)
    empty = sync_dbt_contracts(hub)
    assert empty.items == ()
    assert not empty.sources_dir.exists()
