# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Tests for dbt contract to Bronze vocabulary synchronization."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml
from rdflib import Graph, Literal, URIRef
from rdflib.namespace import RDF

from kairos_ontology.core.dbt_contract_sync import (
    KAIROS_BRONZE,
    KAIROS_DBT,
    DbtContractSyncError,
    sync_dbt_contracts,
)
from kairos_ontology.core.projections.medallion_dbt_projector import _parse_bronze


def _make_hub(tmp_path: Path) -> tuple[Path, Path]:
    hub = tmp_path / "hub"
    models = hub / "integration" / "transforms" / "dbt" / "models"
    models.mkdir(parents=True)
    (models / "int_orders.sql").write_text("select 1\n", encoding="utf-8")
    properties = models / "int_orders.yml"
    properties.write_text(
        yaml.safe_dump(
            {
                "version": 2,
                "models": [
                    {
                        "name": "int_orders",
                        "description": "Conformed orders.",
                        "config": {
                            "materialized": "table",
                            "contract": {"enforced": True},
                        },
                        "meta": {
                            "kairos": {
                                "target_class": "https://example.com/ont#Order",
                                "virtual_source_iri": "https://example.com/source#orders",
                                "grain": "one row per order",
                                "supported_adapters": ["fabric", "databricks"],
                                "grain_key": ["order_id"],
                                "required_packages": [],
                                "required_macros": [],
                            }
                        },
                        "columns": [
                            {
                                "name": "order_id",
                                "description": "Order identifier.",
                                "data_type": "string",
                            },
                            {
                                "name": "amount",
                                "data_type": "decimal(18,2)",
                                "data_tests": ["not_null"],
                            },
                            {"name": "notes", "data_type": "string"},
                        ],
                    }
                ],
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    return hub, properties


def _declare_replacement(hub: Path, properties: Path, table_iri: str) -> None:
    document = yaml.safe_load(properties.read_text(encoding="utf-8"))
    document["models"][0]["meta"]["kairos"]["replaces_sources"] = [{"table_iri": table_iri}]
    properties.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    source_dir = hub / "integration" / "sources" / "erp"
    source_dir.mkdir(parents=True, exist_ok=True)
    graph = Graph()
    graph.add((URIRef(table_iri), RDF.type, KAIROS_BRONZE.SourceTable))
    graph.add((URIRef(table_iri), KAIROS_BRONZE.tableName, Literal("orders_raw")))
    graph.serialize(source_dir / "erp.vocabulary.ttl", format="turtle")


def test_writes_bronze_compatible_graph_with_stable_iris(tmp_path: Path) -> None:
    hub, _ = _make_hub(tmp_path)
    report = sync_dbt_contracts(hub)

    assert report.written_count == 1
    item = report.items[0]
    text = item.output_path.read_text(encoding="utf-8")
    assert "DD-072" in text
    assert "Generated by kairos-ontology-toolkit" in text

    graph = Graph().parse(item.output_path, format="turtle")
    table = URIRef("https://example.com/source#orders")
    column = URIRef("https://example.com/source#orders__order_id")
    assert (table, RDF.type, KAIROS_BRONZE.SourceTable) in graph
    assert (column, RDF.type, KAIROS_BRONZE.SourceColumn) in graph
    assert (table, KAIROS_DBT.sourceKind, None) in graph

    parsed = _parse_bronze(hub / "integration" / "sources")
    assert parsed[0]["tables"][0]["name"] == "int_orders"
    assert {col["name"] for col in parsed[0]["tables"][0]["columns"]} == {
        "order_id",
        "amount",
        "notes",
    }

    columns = {
        str(graph.value(subject, KAIROS_BRONZE.columnName)): subject
        for subject in graph.subjects(RDF.type, KAIROS_BRONZE.SourceColumn)
    }
    assert graph.value(columns["order_id"], KAIROS_BRONZE.nullable).toPython() is False
    assert graph.value(columns["amount"], KAIROS_BRONZE.nullable).toPython() is False
    assert graph.value(columns["notes"], KAIROS_BRONZE.nullable).toPython() is True


def test_semantically_equal_graph_is_not_rewritten(tmp_path: Path) -> None:
    hub, _ = _make_hub(tmp_path)
    first = sync_dbt_contracts(hub)
    output = first.items[0].output_path
    graph = Graph().parse(output, format="turtle")
    alternate = "# Different provenance timestamp\n" + graph.serialize(format="turtle")
    output.write_text(alternate, encoding="utf-8")

    second = sync_dbt_contracts(hub)

    assert second.items[0].state == "unchanged"
    assert second.written_count == 0
    assert output.read_text(encoding="utf-8") == alternate


def test_existing_legacy_column_iris_remain_resolvable_and_are_not_reminted(
    tmp_path: Path,
) -> None:
    hub, _ = _make_hub(tmp_path)
    first = sync_dbt_contracts(hub)
    output = first.items[0].output_path
    graph = Graph().parse(output, format="turtle")
    safe = URIRef("https://example.com/source#orders__order_id")
    legacy = URIRef("https://example.com/source#orders/order_id")
    for subject, predicate, object_ in tuple(graph):
        graph.remove((subject, predicate, object_))
        graph.add(
            (
                legacy if subject == safe else subject,
                predicate,
                legacy if object_ == safe else object_,
            )
        )
    graph.serialize(output, format="turtle")

    second = sync_dbt_contracts(hub)

    assert second.items[0].state == "unchanged"
    preserved = Graph().parse(output, format="turtle")
    assert (legacy, RDF.type, KAIROS_BRONZE.SourceColumn) in preserved
    assert (safe, RDF.type, KAIROS_BRONZE.SourceColumn) not in preserved
    parsed = _parse_bronze(hub / "integration" / "sources")
    parsed_order_id = next(
        column for column in parsed[0]["tables"][0]["columns"] if column["name"] == "order_id"
    )
    assert legacy == URIRef(parsed_order_id["uri"])


def test_sync_emits_validated_source_replacement(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    source_iri = "https://example.com/source/erp#orders_raw"
    _declare_replacement(hub, properties, source_iri)

    report = sync_dbt_contracts(hub)

    graph = Graph().parse(report.items[0].output_path, format="turtle")
    virtual = URIRef("https://example.com/source#orders")
    assert (virtual, KAIROS_DBT.replacesSource, URIRef(source_iri)) in graph


def test_sync_rejects_unknown_source_replacement(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    (hub / "integration" / "sources").mkdir()
    document = yaml.safe_load(properties.read_text(encoding="utf-8"))
    document["models"][0]["meta"]["kairos"]["replaces_sources"] = [
        {"table_iri": "https://example.com/source/erp#missing"}
    ]
    properties.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")

    with pytest.raises(DbtContractSyncError, match="unknown or generated"):
        sync_dbt_contracts(hub)


def test_sync_rejects_duplicate_source_table_authority(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    source_iri = "https://example.com/source/erp#orders_raw"
    _declare_replacement(hub, properties, source_iri)
    duplicate = hub / "integration" / "sources" / "duplicate"
    duplicate.mkdir()
    graph = Graph()
    graph.add((URIRef(source_iri), RDF.type, KAIROS_BRONZE.SourceTable))
    graph.serialize(duplicate / "duplicate.vocabulary.ttl", format="turtle")

    with pytest.raises(DbtContractSyncError, match="conflicting definitions"):
        sync_dbt_contracts(hub)


def test_sync_accepts_equivalent_monolithic_and_split_views(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    source_iri = "https://example.com/source/erp#orders_raw"
    _declare_replacement(hub, properties, source_iri)
    source = hub / "integration" / "sources" / "erp" / "erp.vocabulary.ttl"
    split = hub / "integration" / "sources" / "erp" / "tables" / "orders.vocabulary.ttl"
    split.parent.mkdir()
    split.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")

    report = sync_dbt_contracts(hub)

    assert report.written_count == 1


def test_sync_rejects_divergent_split_view(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    source_iri = "https://example.com/source/erp#orders_raw"
    _declare_replacement(hub, properties, source_iri)
    split = hub / "integration" / "sources" / "erp" / "tables"
    split.mkdir()
    graph = Graph()
    table = URIRef(source_iri)
    column = URIRef(f"{source_iri}/unexpected")
    graph.add((table, RDF.type, KAIROS_BRONZE.SourceTable))
    graph.add((table, KAIROS_BRONZE.tableName, Literal("orders_raw")))
    graph.add((column, RDF.type, KAIROS_BRONZE.SourceColumn))
    graph.add((column, KAIROS_BRONZE.sourceTable, table))
    graph.serialize(split / "orders.vocabulary.ttl", format="turtle")

    with pytest.raises(DbtContractSyncError, match="conflicting definitions"):
        sync_dbt_contracts(hub)


def test_sync_self_heals_malformed_generated_vocabulary(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    source_iri = "https://example.com/source/erp#orders_raw"
    _declare_replacement(hub, properties, source_iri)
    first = sync_dbt_contracts(hub)
    generated = first.items[0].output_path
    generated.write_text("not valid turtle [", encoding="utf-8")

    repaired = sync_dbt_contracts(hub)

    assert repaired.items[0].action == "updated"
    Graph().parse(generated, format="turtle")


def test_check_reports_missing_and_stale_without_writing(tmp_path: Path) -> None:
    hub, properties = _make_hub(tmp_path)
    missing = sync_dbt_contracts(hub, check=True)
    output = missing.items[0].output_path
    assert missing.has_drift
    assert missing.items[0].action == "would_create"
    assert not output.exists()

    sync_dbt_contracts(hub)
    original = output.read_text(encoding="utf-8")
    document = yaml.safe_load(properties.read_text(encoding="utf-8"))
    document["models"][0]["columns"].append({"name": "status", "data_type": "string"})
    properties.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")

    stale = sync_dbt_contracts(hub, check=True)
    assert stale.items[0].state == "stale"
    assert stale.items[0].action == "would_update"
    assert output.read_text(encoding="utf-8") == original

    updated = sync_dbt_contracts(hub)
    assert updated.items[0].action == "updated"
    assert "status" in {
        str(value) for value in Graph().parse(output).objects(None, KAIROS_BRONZE.columnName)
    }


def test_missing_or_empty_transforms_are_successful_noop(tmp_path: Path) -> None:
    hub = tmp_path / "hub"
    hub.mkdir()
    absent = sync_dbt_contracts(hub)
    assert absent.items == ()
    assert not absent.sources_dir.exists()

    (hub / "integration" / "transforms" / "dbt" / "models").mkdir(parents=True)
    empty = sync_dbt_contracts(hub)
    assert empty.items == ()
    assert not empty.sources_dir.exists()


# ---------------------------------------------------------------------------
# Provenance: running toolkit version + prior artifact generator version
# (validation-operations) — never invented, only reported when present.
# ---------------------------------------------------------------------------


def test_report_carries_running_toolkit_version(tmp_path: Path) -> None:
    from kairos_ontology import __version__

    hub, _ = _make_hub(tmp_path)
    report = sync_dbt_contracts(hub)
    assert report.running_toolkit_version == __version__


def test_running_toolkit_version_set_even_without_transforms(tmp_path: Path) -> None:
    from kairos_ontology import __version__

    hub = tmp_path / "hub"
    (hub / "integration").mkdir(parents=True)
    report = sync_dbt_contracts(hub)
    assert report.items == ()
    assert report.running_toolkit_version == __version__


def test_freshly_created_artifact_has_no_prior_generator_version(tmp_path: Path) -> None:
    """No prior file existed, so no provenance can be reported — never invented."""
    hub, _ = _make_hub(tmp_path)
    report = sync_dbt_contracts(hub)
    assert report.items[0].action == "created"
    assert report.items[0].prior_generator_version is None


def test_prior_generator_version_reported_on_regeneration(tmp_path: Path) -> None:
    """When an existing artifact carries a toolkit provenance stamp, drift
    reporting surfaces that *actual* prior version — sourced only from the
    file's own header, never inferred or fabricated."""
    from kairos_ontology.core._provenance import strip_provenance

    hub, properties = _make_hub(tmp_path)
    first = sync_dbt_contracts(hub)
    output_path = first.items[0].output_path

    stale_rule = "# " + "-" * 70
    stale_header = (
        f"{stale_rule}\n"
        "# Generated by kairos-ontology-toolkit v9.9.9-test\n"
        "# Generator : sync-dbt-contracts\n"
        "# Generated : 2020-01-01T00:00:00Z (UTC)\n"
        "# Do not edit by hand — regenerate via the CLI/skill.\n"
        f"{stale_rule}\n\n"
    )
    body = strip_provenance(output_path.read_text(encoding="utf-8"))
    output_path.write_text(stale_header + body, encoding="utf-8")

    # Force drift: change the contract description, which changes the built graph.
    document = yaml.safe_load(properties.read_text(encoding="utf-8"))
    document["models"][0]["description"] = "Conformed orders (updated)."
    properties.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")

    second = sync_dbt_contracts(hub)
    updated_item = second.items[0]
    assert updated_item.action == "updated"
    assert updated_item.prior_generator_version == "9.9.9-test"


def test_unmanaged_existing_file_has_no_prior_generator_version(tmp_path: Path) -> None:
    """An existing file with no toolkit provenance header reports None — the
    absence of a stamp must never be papered over with a guessed version."""
    hub, properties = _make_hub(tmp_path)
    sources_dir = hub / "integration" / "sources" / "custom-transformations"
    sources_dir.mkdir(parents=True)
    output_path = sources_dir / "int_orders.vocabulary.ttl"
    output_path.write_text("# hand-authored, no toolkit header\n", encoding="utf-8")

    report = sync_dbt_contracts(hub)
    assert report.items[0].prior_generator_version is None
