# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Hub-wide bounded-context diagrams under the `ddd` target (DD-230, #846).

Every diagram target selected by file, so nothing could draw a bounded context -- the one
construct that cuts across domain files. These tests pin the hub-wide artifacts, the four
findings from the hub prototype (namespace/class collision, notes out of the diagram,
annotation-gated membership, the canonical ERD's multiplicity helpers), the Silver status
read from authored contracts and bindings, and the projector-level wiring: files land under
`architecture/ddd/contexts/`, the retired per-domain context map is removed, and a renamed
context does not leave its old diagram behind.
"""

from __future__ import annotations

import shutil
import textwrap
from pathlib import Path

import pytest
from rdflib import Graph

from kairos_ontology.core.projections.ddd_context_projector import (
    ALL_CONTEXTS_NAME,
    CONTEXT_MAP_NAME,
    CONTEXTS_SUBDIR,
    DESIGN_NOTES_NAME,
    ContextDomain,
    generate_context_artifacts,
)
from kairos_ontology.core.projector import _PROJECTION_MANIFEST_NAME, run_projections

ACME_HUB = Path(__file__).parent / "scenarios" / "acme-hub"
ONTOLOGIES = ACME_HUB / "model" / "ontologies"
EXTENSIONS = ACME_HUB / "model" / "extensions"
STRATEGIC = EXTENSIONS / "ddd-contexts-ext.ttl"

INVOICE_NS = "https://acme.example/ontology/invoice#"
CLIENT_NS = "https://acme.example/ontology/client#"


def _domain(name: str) -> ContextDomain:
    graph = Graph()
    graph.parse(ONTOLOGIES / f"{name}.ttl", format="turtle")
    return ContextDomain(
        name=name,
        graph=graph,
        file=ONTOLOGIES / f"{name}.ttl",
        local_graph=graph,
        overlay_path=EXTENSIONS / f"{name}-ddd-ext.ttl",
    )


@pytest.fixture(scope="module")
def artifacts() -> dict[str, str]:
    return generate_context_artifacts(
        [_domain("client"), _domain("invoice")], strategic_path=STRATEGIC, hub_name="acme-hub"
    )


def _key(name: str) -> str:
    return f"{CONTEXTS_SUBDIR}/{name}"


class TestArtifactSet:
    def test_one_map_one_overview_one_notes_and_one_file_per_non_empty_context(self, artifacts):
        assert set(artifacts) == {
            _key(CONTEXT_MAP_NAME),
            _key(ALL_CONTEXTS_NAME),
            _key(DESIGN_NOTES_NAME),
            _key("BillingContext.mmd"),
            _key("TaxContext.mmd"),
            _key("ClientContext.mmd"),
            _key("ReferenceContext.mmd"),
        }

    def test_every_diagram_opens_with_the_shared_header(self, artifacts):
        for name, text in artifacts.items():
            if name.endswith(".mmd"):
                assert text.startswith("---\nconfig:\n  layout: elk\n---\n%% Generated by"), name

    def test_deterministic(self):
        first = generate_context_artifacts(
            [_domain("client"), _domain("invoice")], strategic_path=STRATEGIC
        )
        second = generate_context_artifacts(
            [_domain("invoice"), _domain("client")], strategic_path=STRATEGIC
        )
        assert first == second

    def test_no_ddd_input_yields_nothing(self):
        graph = Graph()
        graph.parse(ONTOLOGIES / "client.ttl", format="turtle")
        bare = ContextDomain(name="client", graph=graph, local_graph=graph)
        assert generate_context_artifacts([bare]) == {}


class TestContextMap:
    def test_every_context_and_every_edge_regardless_of_declaring_file(self, artifacts):
        mmd = artifacts[_key(CONTEXT_MAP_NAME)]
        # Billing/Taxation come from the strategic file, Client/Reference from an overlay.
        for label in ("Billing", "Taxation", "Client Management", "Reference Data"):
            assert label in mmd
        assert "ctx_BillingContext -->|Customer-Supplier| ctx_TaxContext" in mmd
        assert "ctx_ClientContext -->|Conformist| ctx_ReferenceContext" in mmd

    def test_subdomain_type_is_shown_and_styled(self, artifacts):
        mmd = artifacts[_key(CONTEXT_MAP_NAME)]
        assert '["Billing<br/><i>core domain</i>"]' in mmd
        assert "class ctx_BillingContext coreDomain" in mmd
        assert "class ctx_TaxContext genericSubdomain" in mmd


class TestClassDiagrams:
    def test_namespace_per_context_with_pattern_annotations(self, artifacts):
        mmd = artifacts[_key(ALL_CONTEXTS_NAME)]
        assert "namespace BillingContext {" in mmd
        assert "<<AggregateRoot>>" in mmd and "<<ValueObject>>" in mmd
        assert "    class Invoice {" in mmd
        assert "string invoiceNumber" in mmd

    def test_member_without_a_context_inherits_its_roots(self, artifacts):
        """InvoiceLine carries only `aggregateRoot acme-inv:Invoice`; it belongs to Billing."""
        billing = artifacts[_key("BillingContext.mmd")]
        namespace = billing.split("namespace BillingContext {", 1)[1].split("\n}", 1)[0]
        assert "class InvoiceLine {" in namespace
        assert "Invoice *-- InvoiceLine : aggregate" in billing

    def test_cross_context_aggregate_is_drawn_not_hidden(self, artifacts):
        """InvoiceLineTax sits in Taxation but is rooted on Invoice in Billing."""
        mmd = artifacts[_key(ALL_CONTEXTS_NAME)]
        tax = mmd.split("namespace TaxContext {", 1)[1].split("\n}", 1)[0]
        assert "class InvoiceLineTax {" in tax
        assert "Invoice *-- InvoiceLineTax : aggregate" in mmd

    def test_neighbours_are_stubs_with_a_reason(self, artifacts):
        """In the Taxation diagram, Invoice is outside the context: a stub saying where it lives."""
        tax = artifacts[_key("TaxContext.mmd")]
        assert "namespace TaxContext {" in tax
        assert "namespace BillingContext" not in tax
        assert "<<context: Billing>>" in tax

    def test_unassigned_hub_class_reached_by_a_member_is_a_stub(self, artifacts):
        """InvoiceTag has a tactical pattern but no context; it is drawn only where reached."""
        mmd = artifacts[_key(ALL_CONTEXTS_NAME)]
        assert "namespace" in mmd
        assert mmd.count("class InvoiceTag {") <= 1

    def test_membership_is_annotation_gated(self, artifacts):
        """No import-closure class appears inside a namespace."""
        mmd = artifacts[_key(ALL_CONTEXTS_NAME)]
        for block in mmd.split("namespace ")[1:]:
            body = block.split("\n}", 1)[0]
            assert "<<bsp/" not in body and "refp" not in body

    def test_namespace_id_never_equals_a_member_class_id(self, tmp_path):
        """Mermaid rejects a class as its own parent; the context id is suffixed instead."""
        ttl = textwrap.dedent(
            """
            @prefix owl: <http://www.w3.org/2002/07/owl#> .
            @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
            @prefix ex: <https://example.test/ontology/party#> .
            <https://example.test/ontology/party> a owl:Ontology .
            ex:Party a owl:Class ; rdfs:label "Party" .
            """
        )
        overlay = textwrap.dedent(
            """
            @prefix kairos-ddd: <https://kairos.cnext.eu/ddd#> .
            @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
            @prefix ex: <https://example.test/ontology/party#> .
            @prefix ctx: <https://example.test/ddd#> .
            ctx:Party a kairos-ddd:BoundedContext ; rdfs:label "Party" .
            ex:Party kairos-ddd:boundedContext ctx:Party .
            """
        )
        onto = tmp_path / "party.ttl"
        onto.write_text(ttl, encoding="utf-8")
        ov = tmp_path / "party-ddd-ext.ttl"
        ov.write_text(overlay, encoding="utf-8")
        graph = Graph()
        graph.parse(onto, format="turtle")
        out = generate_context_artifacts(
            [
                ContextDomain(
                    name="party", graph=graph, file=onto, local_graph=graph, overlay_path=ov
                )
            ]
        )
        mmd = out[_key(ALL_CONTEXTS_NAME)]
        assert "namespace Party_context {" in mmd
        assert "    class Party {" in mmd


CONTRACT = textwrap.dedent(
    f"""
    apiVersion: kairos.eu/v5
    kind: SilverContract
    metadata:
      domain: invoice
    entities:
      - class: {INVOICE_NS}Invoice
        modelName: invoice
        stability: preview
        closed: true
        grain:
          columns: [invoice_number]
        identity:
          strategy: source-natural
          businessKey: [invoice_number]
        properties:
          - property: {INVOICE_NS}invoiceNumber
            type: string(64)
            requirement: required
            nullable: false
    """
).strip()

BINDING = textwrap.dedent(
    f"""
    apiVersion: kairos.eu/v5
    kind: EntityBinding
    metadata:
      name: billing-invoice-lines
      domain: invoice
    source:
      relation: billing.invoice_lines
    target:
      class: {INVOICE_NS}InvoiceLine
    """
).strip()


class TestSilverStatus:
    @pytest.fixture
    def with_silver(self, tmp_path) -> dict[str, str]:
        contracts = tmp_path / "contracts"
        contracts.mkdir()
        (contracts / "invoice.contract.yaml").write_text(CONTRACT, encoding="utf-8")
        bindings = tmp_path / "bindings"
        bindings.mkdir()
        (bindings / "billing-invoice-lines.binding.yaml").write_text(BINDING, encoding="utf-8")
        return generate_context_artifacts(
            [_domain("client"), _domain("invoice")],
            strategic_path=STRATEGIC,
            contracts_dir=contracts,
            bindings_dir=bindings,
            hub_name="acme-hub",
        )

    def test_status_comes_from_contract_then_binding_then_nothing(self, with_silver):
        notes = with_silver[_key(DESIGN_NOTES_NAME)]
        assert "| Invoice | invoice | AggregateRoot | — | in Silver contract |" in notes
        assert (
            "| Invoice Line | invoice | AggregateMember | Invoice | bound (no contract) |" in notes
        )
        assert "| Invoice Line Tax | invoice | AggregateMember | Invoice | not in Silver |" in notes

    def test_status_is_a_second_stereotype_on_every_member(self, with_silver):
        """Plain-text annotations render everywhere; classDef styling in a classDiagram
        fails the mermaid-cli 11.12 parse, so status is never styling."""
        mmd = with_silver[_key(ALL_CONTEXTS_NAME)]

        def block(name: str) -> str:
            return mmd.split(f"    class {name} {{", 1)[1].split("\n    }", 1)[0]

        assert "<<silver: contract>>" in block("Invoice")
        assert "<<silver: bound>>" in block("InvoiceLine")
        assert "<<architecture only>>" in block("InvoiceLineTax")
        assert "classDef" not in mmd and "cssClass" not in mmd

    def test_default_is_not_in_silver(self, artifacts):
        notes = artifacts[_key(DESIGN_NOTES_NAME)]
        # The legend names every status; only the table rows say what applies.
        assert "| in Silver contract |" not in notes and "| bound (no contract) |" not in notes
        assert "| Invoice | invoice | AggregateRoot | — | not in Silver |" in notes

    def test_a_recorded_disposition_says_why_a_class_is_not_in_silver(self, tmp_path):
        """DD-231 ledger present: the Silver column carries the reason, not just the fact."""
        ledger = tmp_path / "integration" / "discovery" / "class-dispositions.yaml"
        ledger.parent.mkdir(parents=True)
        ledger.write_text(
            textwrap.dedent(
                f"""
                schema_version: 1
                classes:
                  - class: {INVOICE_NS}InvoiceLineTax
                    disposition: architecture-only
                    rationale: tax detail stays in the Taxation context until a source exists
                    decided_by: user
                """
            ),
            encoding="utf-8",
        )
        out = generate_context_artifacts(
            [_domain("invoice")], strategic_path=STRATEGIC, hub_root=tmp_path
        )
        notes = out[_key(DESIGN_NOTES_NAME)]
        assert (
            "| Invoice Line Tax | invoice | AggregateMember | Invoice | not in Silver (architecture-only) |"
            in notes
        )
        assert "| Invoice | invoice | AggregateRoot | — | not in Silver |" in notes

    def test_a_qname_without_a_load_result_is_reported_not_guessed(self, tmp_path):
        contracts = tmp_path / "contracts"
        contracts.mkdir()
        (contracts / "invoice.contract.yaml").write_text(
            CONTRACT.replace(f"class: {INVOICE_NS}Invoice", "class: acme-inv:Invoice"),
            encoding="utf-8",
        )
        out = generate_context_artifacts(
            [_domain("invoice")], strategic_path=STRATEGIC, contracts_dir=contracts
        )
        notes = out[_key(DESIGN_NOTES_NAME)]
        assert "## Unresolved class references" in notes
        assert "invoice.contract.yaml: acme-inv:Invoice" in notes


class TestDesignNotes:
    def test_grouped_by_context_with_invariants_language_and_backlog(self, artifacts):
        notes = artifacts[_key(DESIGN_NOTES_NAME)]
        assert "## Billing — Core Domain (published language)" in notes
        assert "## Taxation — Generic Subdomain" in notes
        assert "- **Invoice:** An invoice total equals the sum of its line amounts." in notes
        assert "scope: In Billing an invoice is the issued document" in notes
        assert "also called: Bill" in notes
        assert "examples: INV-2026-000123" in notes
        assert "## Classes outside any bounded context" in notes
        assert "| Invoice Tag | invoice | not in Silver |" in notes

    def test_notes_carry_no_timestamp(self, artifacts):
        assert "Generated :" not in artifacts[_key(DESIGN_NOTES_NAME)]


@pytest.fixture
def hub(tmp_path: Path) -> Path:
    destination = tmp_path / "hub"
    shutil.copytree(ACME_HUB, destination)
    return destination


def _project_ddd(hub: Path, output: Path) -> None:
    run_projections(
        ontologies_path=hub / "model" / "ontologies",
        catalog_path=None,
        output_path=output,
        target="ddd",
    )


class TestProjectorWiring:
    def test_context_artifacts_land_under_the_ddd_target(self, hub, tmp_path):
        output = tmp_path / "publish"
        _project_ddd(hub, output)
        ddd = output / "architecture" / "ddd"
        assert (ddd / "client-aggregate-overview.mmd").is_file()
        assert (ddd / CONTEXTS_SUBDIR / CONTEXT_MAP_NAME).is_file()
        assert (ddd / CONTEXTS_SUBDIR / ALL_CONTEXTS_NAME).is_file()
        assert (ddd / CONTEXTS_SUBDIR / "BillingContext.mmd").is_file()
        assert (ddd / _PROJECTION_MANIFEST_NAME).is_file()
        assert not (ddd / "client-context-map.mmd").exists()

    def test_the_retired_per_domain_context_map_is_removed_once(self, hub, tmp_path):
        """An earlier toolkit wrote it and no manifest owns it, so it is named explicitly."""
        output = tmp_path / "publish"
        ddd = output / "architecture" / "ddd"
        ddd.mkdir(parents=True)
        (ddd / "client-context-map.mmd").write_text("graph LR\n", encoding="utf-8")
        _project_ddd(hub, output)
        assert not (ddd / "client-context-map.mmd").exists()

    def test_a_renamed_context_does_not_leave_its_diagram_behind(self, hub, tmp_path):
        output = tmp_path / "publish"
        _project_ddd(hub, output)
        contexts = output / "architecture" / "ddd" / CONTEXTS_SUBDIR
        assert (contexts / "TaxContext.mmd").is_file()

        strategic = hub / "model" / "extensions" / "ddd-contexts-ext.ttl"
        overlay = hub / "model" / "extensions" / "invoice-ddd-ext.ttl"
        for path in (strategic, overlay):
            path.write_text(
                path.read_text(encoding="utf-8").replace("TaxContext", "TaxationContext"),
                encoding="utf-8",
            )
        _project_ddd(hub, output)
        assert (contexts / "TaxationContext.mmd").is_file()
        assert not (contexts / "TaxContext.mmd").exists()

    def test_a_hub_without_ddd_input_gets_no_contexts(self, hub, tmp_path):
        """No overlay, no strategic file: no `contexts/`. The manifest still exists, because
        DD-232's language artifacts are written for every hub with a class."""
        for path in (hub / "model" / "extensions").glob("*ddd*"):
            path.unlink()
        output = tmp_path / "publish"
        _project_ddd(hub, output)
        ddd = output / "architecture" / "ddd"
        assert not (ddd / CONTEXTS_SUBDIR).exists()
        assert (ddd / _PROJECTION_MANIFEST_NAME).is_file()
        assert (ddd / "ubiquitous-language.ttl").is_file()
