# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Every generated Mermaid diagram opens with frontmatter selecting the ELK layout (#855).

Layout is chosen by the diagram, not the viewer: without frontmatter a reader has no way
to ask for ELK short of editing a file marked "do not edit". The frontmatter is emitted by
one shared helper so the order -- frontmatter, then the provenance stamp, then the diagram
keyword -- cannot drift between projectors, and the master-ERD merges strip each part's
header so the merged file carries exactly one.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from kairos_ontology.core.projections.medallion_gold_projector import generate_master_gold_erd
from kairos_ontology.core.projections.medallion_silver_projector import generate_master_erd
from kairos_ontology.core.projections.shared import (
    MERMAID_LAYOUT_ELK,
    MERMAID_LAYOUT_NONE,
    configure_mermaid_layout,
    current_mermaid_layout,
    mermaid_frontmatter,
    mermaid_header,
    mermaid_provenance_comment,
    strip_mermaid_header,
)

FRONTMATTER = ["---", "config:", "  layout: elk", "---"]


@pytest.fixture(autouse=True)
def _default_layout():
    """The setting is process-wide; every test starts and ends on the default."""
    configure_mermaid_layout(None)
    yield
    configure_mermaid_layout(None)


def _hub(tmp_path: Path, config: str | None) -> Path:
    hub = tmp_path / "hub"
    hub.mkdir()
    if config is not None:
        (hub / "kairos.yaml").write_text(textwrap.dedent(config), encoding="utf-8")
    return hub


class TestHeader:
    def test_frontmatter_precedes_the_provenance_stamp(self):
        assert mermaid_header(indent="") == [*FRONTMATTER, mermaid_provenance_comment(indent="")]

    def test_frontmatter_sits_at_column_zero_whatever_the_stamp_indent(self):
        header = mermaid_header()  # default indent is four spaces, for erDiagram bodies
        assert header[:4] == FRONTMATTER
        # The fences and the `config:` key sit at column 0; only YAML's own two-space
        # nesting indents the layout line, never the stamp indent.
        assert [header[0], header[1], header[3]] == ["---", "config:", "---"]
        assert header[2] == "  layout: elk"
        assert header[4].startswith("    %% Generated by kairos-ontology")

    def test_default_is_elk_without_a_hub(self):
        assert configure_mermaid_layout(None) == MERMAID_LAYOUT_ELK
        assert mermaid_frontmatter() == FRONTMATTER


class TestConfiguration:
    def test_missing_config_defaults_to_elk(self, tmp_path):
        assert configure_mermaid_layout(_hub(tmp_path, None)) == MERMAID_LAYOUT_ELK

    def test_none_opts_the_whole_hub_out(self, tmp_path):
        hub = _hub(tmp_path, "projections:\n  mermaid_layout: none\n")
        assert configure_mermaid_layout(hub) == MERMAID_LAYOUT_NONE
        assert mermaid_frontmatter() == []
        assert mermaid_header(indent="") == [mermaid_provenance_comment(indent="")]

    def test_unknown_value_keeps_elk_and_says_so(self, tmp_path, capsys):
        hub = _hub(tmp_path, "projections:\n  mermaid_layout: dagre\n")
        assert configure_mermaid_layout(hub) == MERMAID_LAYOUT_ELK
        out = capsys.readouterr().out
        assert "projections.mermaid_layout" in out and "'dagre'" in out and "elk, none" in out

    def test_a_later_hub_resets_an_earlier_opt_out(self, tmp_path):
        configure_mermaid_layout(_hub(tmp_path, "projections:\n  mermaid_layout: none\n"))
        assert current_mermaid_layout() == MERMAID_LAYOUT_NONE
        other = tmp_path / "other"
        other.mkdir()
        assert configure_mermaid_layout(other) == MERMAID_LAYOUT_ELK


class TestStrip:
    def test_removes_a_leading_block_and_every_stamp(self):
        lines = [
            *FRONTMATTER,
            "%% Generated by kairos-ontology 1 -- do not edit",
            "erDiagram",
            "  A {",
        ]
        assert strip_mermaid_header(lines) == ["erDiagram", "  A {"]

    def test_leaves_a_body_without_frontmatter_alone(self):
        assert strip_mermaid_header(["erDiagram", "  A {", "  }"]) == ["erDiagram", "  A {", "  }"]

    def test_only_a_block_opening_on_the_first_line_is_frontmatter(self):
        lines = ["erDiagram", "---", "  A {"]
        assert strip_mermaid_header(lines) == lines

    def test_an_unterminated_block_yields_nothing_rather_than_garbage(self):
        assert strip_mermaid_header(["---", "config:", "  layout: elk"]) == []


def _silver_part(domain: str) -> str:
    return "\n".join(
        [
            *FRONTMATTER,
            "erDiagram",
            "    %% Generated by kairos-ontology 9.9.9 -- do not edit",
            f"    %% Silver ERD: {domain}; adapter=fabric-warehouse/1",
            f"    {domain.upper()} {{",
            f"        string {domain}_id PK",
            "    }",
            "",
        ]
    )


def _gold_part(domain: str) -> str:
    return "\n".join(
        [
            *FRONTMATTER,
            "erDiagram",
            "    %% Generated by kairos-ontology 9.9.9 -- do not edit",
            "    %% Gold product dimensional-powerbi-v1/1; adapter=fabric-warehouse",
            f"    DIM_{domain.upper()} {{",
            f"        string {domain}_sk PK",
            "    }",
            "",
        ]
    )


class TestMasterMerges:
    def test_master_silver_erd_carries_exactly_one_header(self, tmp_path):
        for domain in ("party", "billing"):
            (tmp_path / f"{domain}-erd.mmd").write_text(_silver_part(domain), encoding="utf-8")
        text = generate_master_erd(tmp_path, "acme")
        assert text is not None
        assert text.startswith("---\nconfig:\n  layout: elk\n---\nerDiagram\n    %% Generated by")
        assert text.count("layout: elk") == 1
        assert text.count("%% Generated by kairos-ontology") == 1
        assert "PARTY {" in text and "BILLING {" in text

    def test_master_gold_erd_carries_exactly_one_header(self, tmp_path):
        for domain in ("party", "billing"):
            (tmp_path / f"{domain}-gold-erd.mmd").write_text(_gold_part(domain), encoding="utf-8")
        text = generate_master_gold_erd(tmp_path, hub_name="acme")
        assert text is not None
        assert text.startswith("---\nconfig:\n  layout: elk\n---\nerDiagram\n    %% Generated by")
        assert text.count("layout: elk") == 1
        assert text.count("%% Generated by kairos-ontology") == 1
        assert "DIM_PARTY {" in text and "DIM_BILLING {" in text

    def test_opted_out_hub_merges_parts_written_before_the_opt_out(self, tmp_path):
        """A hub that turns frontmatter off still has old per-domain files carrying it."""
        (tmp_path / "party-erd.mmd").write_text(_silver_part("party"), encoding="utf-8")
        configure_mermaid_layout(_hub(tmp_path, "projections:\n  mermaid_layout: none\n"))
        text = generate_master_erd(tmp_path, "acme")
        assert text is not None
        assert text.startswith("erDiagram\n")
        assert "layout: elk" not in text
