# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""The canonical ERD target gains a hub-wide master diagram (#753).

The bound Silver and Gold families already merge their per-domain ERDs into a master; the
canonical target did not, so a reader wanting the whole canonical surface had to open every
domain file and hold them in their head.

`medallion_silver_projector.generate_master_erd` is deliberately **not** reused. It emits
and merges `erDiagram` bodies while this target emits `classDiagram` — different dialect,
member syntax and edge syntax — so feeding one into the other produces a file Mermaid
cannot parse. Its cross-domain block is also synthesised from `*-silver-constraints.json`,
which is compile-plan-derived, while this target is binding-independent by construction
(DD-209).

The real work is deduplication: an imported class is drawn in every domain that reaches it.
"""

from __future__ import annotations

from pathlib import Path

from kairos_ontology.core.projections.erd_projector import (
    MASTER_CLASS_DIAGRAM_NAME,
    generate_master_class_diagram,
)

_PARTY = """\
%% Generated by kairos-ontology 0.0.0 -- do not edit
%% Canonical ontology class diagram: binding-independent.
classDiagram
    class Customer {
        string customerId
        string customerName
    }
    class Country {
        string code
    }
    Customer "0..*" --> "0..*" Country : country
"""

# `billing` reaches `Customer` across a domain boundary, so it draws it with a stereotype.
_BILLING = """\
%% Generated by kairos-ontology 0.0.0 -- do not edit
classDiagram
    class Invoice {
        decimal amount
    }
    class Customer {
        <<ontology/party>>
        string customerId
        string customerName
    }
    Invoice "0..*" --> "0..*" Customer : billedTo
"""


def _hub(tmp_path: Path, **domains: str) -> Path:
    for domain, text in domains.items():
        (tmp_path / f"{domain}-erd.mmd").write_text(text, encoding="utf-8")
    return tmp_path


class TestMerge:
    def test_every_domain_contributes(self, tmp_path):
        text = generate_master_class_diagram(_hub(tmp_path, party=_PARTY, billing=_BILLING))
        for node in ("Customer", "Country", "Invoice"):
            assert f"class {node} {{" in text, node

    def test_a_class_drawn_by_two_domains_appears_once(self, tmp_path):
        """Naive concatenation emits it twice and Mermaid merges them into one node with
        the members repeated."""
        text = generate_master_class_diagram(_hub(tmp_path, party=_PARTY, billing=_BILLING))
        assert text.count("class Customer {") == 1
        assert text.count("string customerName") == 1

    def test_the_owning_domain_s_drawing_wins(self, tmp_path):
        """A stereotype marks a class as imported *from the drawing domain's view*. In the
        merged hub-wide diagram every domain is local, so the owner's drawing is right and
        the importer's is misleading."""
        text = generate_master_class_diagram(_hub(tmp_path, party=_PARTY, billing=_BILLING))
        block = text.split("class Customer {")[1].split("}")[0]
        assert "<<ontology/party>>" not in block
        assert "customerName" in block

    def test_a_stub_never_beats_a_full_rendering(self, tmp_path):
        stub = "classDiagram\n    class Customer {\n        <<ont/ref>>\n    }\n"
        text = generate_master_class_diagram(_hub(tmp_path, party=_PARTY, zz=stub))
        assert "customerName" in text.split("class Customer {")[1].split("}")[0]

    def test_edges_are_deduplicated_and_both_kept(self, tmp_path):
        text = generate_master_class_diagram(_hub(tmp_path, party=_PARTY, billing=_BILLING))
        assert text.count(": country") == 1
        assert text.count(": billedTo") == 1

    def test_it_renders_one_classdiagram_header(self, tmp_path):
        """Merging per-domain files each carrying their own header is how a Mermaid file
        stops parsing."""
        text = generate_master_class_diagram(_hub(tmp_path, party=_PARTY, billing=_BILLING))
        assert text.count("classDiagram") == 1
        assert text.splitlines()[0].startswith("%% Generated by kairos-ontology")

    def test_the_output_is_deterministic(self, tmp_path):
        hub = _hub(tmp_path, party=_PARTY, billing=_BILLING)
        assert generate_master_class_diagram(hub) == generate_master_class_diagram(hub)


class TestNothingToMerge:
    def test_an_absent_directory_returns_none(self, tmp_path):
        assert generate_master_class_diagram(tmp_path / "nope") is None

    def test_an_empty_directory_returns_none(self, tmp_path):
        """Reported by the caller, rather than writing an empty diagram."""
        assert generate_master_class_diagram(tmp_path) is None

    def test_a_previous_master_is_not_merged_into_itself(self, tmp_path):
        hub = _hub(tmp_path, party=_PARTY)
        (hub / MASTER_CLASS_DIAGRAM_NAME).write_text(
            generate_master_class_diagram(hub), encoding="utf-8"
        )
        assert generate_master_class_diagram(hub).count("class Customer {") == 1
