# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Undeclared workflow drift fails `update --check`; declared drift does not (#772).

The shipped workflows carry `# Auto-generated by kairos-ontology-toolkit`, but a locally
edited one was reported informationally and the run then printed "All managed files are up
to date" and exited 0. Two failure modes followed: a hub made a deliberate CI fix, got no
signal, and had it reverted by the next `update`; and the `managed-check` workflow — whose
whole purpose is catching this — stayed green, so a green result read as "no drift" when it
meant "no drift in the files the check covers".

Simply failing on any divergence is ruled out on purpose. `cli/workflow_refresh` states
that workflows legitimately carry local customization and that failing CI whenever they
diverge "would be wrong" — which is why they were kept out of the marker-based managed-file
mechanism. So divergence became *declarable*: undeclared drift fails, declared drift is
reported and left alone.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from click.testing import CliRunner

from kairos_ontology.cli.main import cli
from kairos_ontology.cli.shared import (
    DECLARED_WORKFLOWS_KEY,
    declared_customized_workflows,
)

_WORKFLOW = ".github/workflows/pr-validate.yml"
_SCAFFOLD = Path(__file__).resolve().parents[1] / "src" / "kairos_ontology" / "scaffold"
_WINDOWS_PATH = ".github" + chr(92) + "workflows" + chr(92) + "pr-validate.yml"


@pytest.fixture
def runner():
    return CliRunner()


def _hub(tmp_path: Path, *, declared: list[str] | None = None) -> Path:
    """A hub carrying the shipped pr-validate.yml, optionally declaring an edit."""
    declaration = ""
    if declared is not None:
        entries = "".join('  "{}",\n'.format(item) for item in declared)
        declaration = "{} = [\n{}]\n".format(DECLARED_WORKFLOWS_KEY, entries)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "test-hub"\n\ndependencies = [\n'
        '  "kairos-ontology-toolkit @ https://github.com/Cnext-eu/kairos-ontology-toolkit'
        '/releases/download/v3.8.0/kairos_ontology_toolkit-0.0.0-py3-none-any.whl",\n]\n\n'
        '[tool.kairos]\nchannel = "preview"\n' + declaration,
        encoding="utf-8",
    )
    destination = tmp_path / _WORKFLOW
    destination.parent.mkdir(parents=True, exist_ok=True)
    shipped = (_SCAFFOLD / "github-workflows" / "pr-validate.yml").read_text(encoding="utf-8")
    destination.write_text(shipped, encoding="utf-8")
    return tmp_path


def _populate(runner: CliRunner, hub: Path, monkeypatch) -> None:
    """Run a real `update` so the hub is otherwise complete.

    Without this the exit code is decided by ~57 missing managed files and says nothing
    about workflow drift, which is the only thing these tests are about.
    """
    monkeypatch.chdir(hub)
    runner.invoke(cli, ["update", "--refresh-workflows"])


def _edit(hub: Path) -> None:
    """The shape of edit a hub actually makes: one extra step in a real job."""
    path = hub / _WORKFLOW
    path.write_text(
        path.read_text(encoding="utf-8").replace(
            "      - name: Install toolkit\n",
            "      - name: Install org CA bundle\n        run: ./ci/install-ca.sh\n\n"
            "      - name: Install toolkit\n",
            1,
        ),
        encoding="utf-8",
    )


class TestDeclarationReader:
    def test_absent_pyproject_declares_nothing(self, tmp_path):
        assert declared_customized_workflows(tmp_path) == frozenset()

    def test_malformed_pyproject_declares_nothing_rather_than_raising(self, tmp_path):
        """This decides whether to *fail* a check, so it must not fail closed on a file
        some other tool owns."""
        (tmp_path / "pyproject.toml").write_text("[project\nbroken", encoding="utf-8")
        assert declared_customized_workflows(tmp_path) == frozenset()

    def test_declarations_are_read(self, tmp_path):
        (tmp_path / "pyproject.toml").write_text(
            '[tool.kairos]\n{} = ["{}"]\n'.format(DECLARED_WORKFLOWS_KEY, _WORKFLOW),
            encoding="utf-8",
        )
        assert declared_customized_workflows(tmp_path) == frozenset({_WORKFLOW})

    def test_a_windows_style_path_is_normalised(self, tmp_path):
        """A TOML *literal* string keeps backslashes literal, which is how a Windows path
        gets written without double-escaping. Both spellings must mean one workflow."""
        (tmp_path / "pyproject.toml").write_text(
            "[tool.kairos]\n{} = ['{}']\n".format(DECLARED_WORKFLOWS_KEY, _WINDOWS_PATH),
            encoding="utf-8",
        )
        assert declared_customized_workflows(tmp_path) == frozenset({_WORKFLOW})

    def test_a_non_list_value_is_ignored(self, tmp_path):
        (tmp_path / "pyproject.toml").write_text(
            '[tool.kairos]\n{} = "pr-validate.yml"\n'.format(DECLARED_WORKFLOWS_KEY),
            encoding="utf-8",
        )
        assert declared_customized_workflows(tmp_path) == frozenset()


class TestUpdateCheckGate:
    def test_an_unedited_workflow_does_not_trip_the_gate(self, runner, tmp_path, monkeypatch):
        hub = _hub(tmp_path)
        _populate(runner, hub, monkeypatch)

        result = runner.invoke(cli, ["update", "--check"])

        assert "differ from the shipped template" not in result.output
        assert result.exit_code == 0, result.output

    def test_undeclared_drift_fails_the_check(self, runner, tmp_path, monkeypatch):
        hub = _hub(tmp_path)
        _populate(runner, hub, monkeypatch)
        _edit(hub)

        result = runner.invoke(cli, ["update", "--check"])

        assert result.exit_code == 1, result.output
        assert _WORKFLOW in result.output
        # It must not also claim everything is fine — that false assurance is half the bug.
        assert "All managed files are up to date" not in result.output
        # And it must say how to resolve it, not merely that something is wrong.
        assert DECLARED_WORKFLOWS_KEY in result.output

    def test_declared_drift_passes_and_is_still_reported(self, runner, tmp_path, monkeypatch):
        hub = _hub(tmp_path, declared=[_WORKFLOW])
        _populate(runner, hub, monkeypatch)
        _edit(hub)

        result = runner.invoke(cli, ["update", "--check"])

        assert result.exit_code == 0, result.output
        assert "declared workflow customization" in result.output
        assert _WORKFLOW in result.output

    def test_declaring_one_workflow_does_not_excuse_another(
        self, runner, tmp_path, monkeypatch
    ):
        """The declaration is per file, so it cannot become a blanket opt-out."""
        hub = _hub(tmp_path, declared=[".github/workflows/full-validate.yml"])
        _populate(runner, hub, monkeypatch)
        _edit(hub)

        result = runner.invoke(cli, ["update", "--check"])

        assert result.exit_code == 1, result.output
        assert _WORKFLOW in result.output
