# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""DDD documentation projector (DD-091).

One-way, documentation-only projection of the Domain-Driven Design overlay into:

- ``{domain}-context-map.mmd``       — Mermaid context map (bounded contexts + edges)
- ``{domain}-aggregate-overview.mmd``— Mermaid aggregate/tactical-pattern overview
- ``{domain}-ddd-report.md``         — Markdown architecture report

Output is deterministic (sorted, no embedded timestamps) and never influences
silver/gold/dbt/Power BI generation.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from rdflib import Graph, Namespace, URIRef
from rdflib.namespace import RDF, RDFS

from .uri_utils import extract_local_name

DDD = Namespace("https://kairos.cnext.eu/ddd#")


def _sanitize(node_id: str) -> str:
    """Make a Mermaid-safe node id from a local name."""
    return re.sub(r"[^0-9A-Za-z_]", "_", node_id)


def _label(graph: Graph, uri: URIRef) -> str:
    """Return rdfs:label if present, else the local name."""
    lbl = graph.value(uri, RDFS.label)
    return str(lbl) if lbl else extract_local_name(str(uri))


def _merge_overlay(graph: Graph, overlay_path: Optional[Path]) -> Graph:
    """Return a graph combining the domain graph, the overlay, and the DDD vocab.

    The vocabulary is merged so controlled-individual labels (tactical patterns,
    relationship patterns) resolve for rendering.
    """
    merged = Graph()
    for triple in graph:
        merged.add(triple)
    if overlay_path and Path(overlay_path).exists():
        merged.parse(overlay_path, format="turtle")
    from ..ddd import load_ddd_vocabulary

    for triple in load_ddd_vocabulary():
        merged.add(triple)
    return merged


def _collect(graph: Graph) -> dict:
    """Extract DDD structures from a merged graph."""
    contexts = sorted(set(graph.subjects(RDF.type, DDD.BoundedContext)), key=str)

    relationships = []
    for rel in sorted(set(graph.subjects(RDF.type, DDD.ContextRelationship)), key=str):
        src = graph.value(rel, DDD.sourceContext)
        tgt = graph.value(rel, DDD.targetContext)
        pattern = graph.value(rel, DDD.relationshipPattern)
        relationships.append((rel, src, tgt, pattern))

    # class -> tactical pattern
    tactical: dict[URIRef, URIRef] = {}
    for cls, pat in graph.subject_objects(DDD.tacticalPattern):
        tactical[cls] = pat

    # aggregate member -> root
    members: dict[URIRef, URIRef] = {}
    for member, root in graph.subject_objects(DDD.aggregateRoot):
        members[member] = root

    # class -> bounded context assignment
    assignments: dict[URIRef, URIRef] = {}
    for elem, ctx in graph.subject_objects(DDD.boundedContext):
        assignments[elem] = ctx

    published = set()
    for subj, val in graph.subject_objects(DDD.publishedLanguage):
        if str(val).lower() in ("true", "1"):
            published.add(subj)

    notes: list[tuple[URIRef, str]] = []
    for subj, note in graph.subject_objects(DDD.designNote):
        notes.append((subj, str(note)))
    notes.sort(key=lambda x: str(x[0]))

    return {
        "contexts": contexts,
        "relationships": relationships,
        "tactical": tactical,
        "members": members,
        "assignments": assignments,
        "published": published,
        "notes": notes,
    }


def _has_content(data: dict) -> bool:
    return bool(
        data["contexts"]
        or data["relationships"]
        or data["tactical"]
        or data["members"]
    )


def _context_map_mmd(graph: Graph, data: dict, domain: str) -> str:
    lines = ["%% DDD context map (generated by kairos-ontology — do not edit)",
             "graph LR"]
    for ctx in data["contexts"]:
        node = _sanitize(extract_local_name(str(ctx)))
        lines.append(f'    ctx_{node}["{_label(graph, ctx)}"]')
    for _rel, src, tgt, pattern in data["relationships"]:
        if src is None or tgt is None:
            continue
        s = _sanitize(extract_local_name(str(src)))
        t = _sanitize(extract_local_name(str(tgt)))
        if pattern is not None:
            edge = _label(graph, pattern) if isinstance(pattern, URIRef) else str(pattern)
            lines.append(f'    ctx_{s} -->|{edge}| ctx_{t}')
        else:
            lines.append(f'    ctx_{s} --> ctx_{t}')
    return "\n".join(lines) + "\n"


def _aggregate_overview_mmd(graph: Graph, data: dict, domain: str) -> str:
    lines = ["%% DDD aggregate overview (generated by kairos-ontology — do not edit)",
             "graph TD"]

    # Group aggregate members by root.
    roots: dict[URIRef, list[URIRef]] = {}
    for member, root in sorted(data["members"].items(), key=lambda x: str(x[0])):
        roots.setdefault(root, []).append(member)

    rendered: set[str] = set()

    def node(cls: URIRef) -> str:
        nid = _sanitize(extract_local_name(str(cls)))
        if nid not in rendered:
            pat = data["tactical"].get(cls)
            stereotype = f"«{extract_local_name(str(pat))}»<br/>" if pat is not None else ""
            lines.append(f'    {nid}["{stereotype}{_label(graph, cls)}"]')
            rendered.add(nid)
        return nid

    for root in sorted(roots, key=str):
        rnode = node(root)
        for member in roots[root]:
            mnode = node(member)
            lines.append(f"    {rnode} --> {mnode}")

    # Classes with a tactical pattern but not part of an aggregate edge.
    for cls in sorted(data["tactical"], key=str):
        if cls not in data["members"] and cls not in roots:
            node(cls)

    return "\n".join(lines) + "\n"


def _report_md(graph: Graph, data: dict, domain: str, meta: dict) -> str:
    version = meta.get("toolkit_version", "")
    lines = [
        f"# DDD Architecture Overview — {domain}",
        "",
        "> Generated by `kairos-ontology project --target ddd` (DD-091). "
        "Documentation only — not a governance or projection-control source.",
        "",
    ]
    if version:
        lines += [f"**Toolkit version:** {version}", ""]

    # Bounded contexts
    lines += ["## Bounded Contexts", ""]
    if data["contexts"]:
        lines += ["| Context | Published Language | Note |",
                  "|---------|--------------------|------|"]
        note_map = {s: n for s, n in data["notes"]}
        for ctx in data["contexts"]:
            pub = "yes" if ctx in data["published"] else "—"
            note = note_map.get(ctx, "—")
            lines.append(f"| {_label(graph, ctx)} | {pub} | {note} |")
    else:
        lines.append("_No bounded contexts declared._")
    lines.append("")

    # Context relationships
    lines += ["## Context Map", ""]
    if data["relationships"]:
        lines += ["| Source | Pattern | Target |",
                  "|--------|---------|--------|"]
        for _rel, src, tgt, pattern in data["relationships"]:
            s = _label(graph, src) if src is not None else "—"
            t = _label(graph, tgt) if tgt is not None else "—"
            p = _label(graph, pattern) if isinstance(pattern, URIRef) else (str(pattern) if pattern else "—")
            lines.append(f"| {s} | {p} | {t} |")
    else:
        lines.append("_No context relationships declared._")
    lines.append("")

    # Aggregates
    lines += ["## Aggregates & Tactical Patterns", ""]
    if data["tactical"] or data["members"]:
        roots: dict[URIRef, list[URIRef]] = {}
        for member, root in data["members"].items():
            roots.setdefault(root, []).append(member)
        lines += ["| Class | Tactical Pattern | Aggregate Root |",
                  "|-------|------------------|----------------|"]
        classes = sorted(set(data["tactical"]) | set(data["members"]) | set(roots), key=str)
        for cls in classes:
            pat = data["tactical"].get(cls)
            pat_label = extract_local_name(str(pat)) if pat is not None else "—"
            root = data["members"].get(cls)
            root_label = _label(graph, root) if root is not None else (
                "(root)" if cls in roots else "—"
            )
            lines.append(f"| {_label(graph, cls)} | {pat_label} | {root_label} |")
    else:
        lines.append("_No tactical patterns declared._")
    lines.append("")

    # Design notes
    if data["notes"]:
        lines += ["## Design Notes", ""]
        for subj, note in data["notes"]:
            lines.append(f"- **{_label(graph, subj)}:** {note}")
        lines.append("")

    return "\n".join(lines)


def generate_ddd_artifacts(
    graph: Graph,
    namespace: str,
    ontology_name: str,
    overlay_path: Optional[Path] = None,
    ontology_metadata: Optional[dict] = None,
) -> dict:
    """Generate DDD documentation artifacts from the domain graph + overlay.

    Returns ``{}`` when the overlay contains no DDD content (feature is optional).
    """
    merged = _merge_overlay(graph, overlay_path)
    data = _collect(merged)
    if not _has_content(data):
        return {}

    domain = ontology_name or "domain"
    meta = ontology_metadata or {}
    return {
        f"{domain}-context-map.mmd": _context_map_mmd(merged, data, domain),
        f"{domain}-aggregate-overview.mmd": _aggregate_overview_mmd(merged, data, domain),
        f"{domain}-ddd-report.md": _report_md(merged, data, domain, meta),
    }
