# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""The hub's ubiquitous language as a generated SKOS vocabulary (DD-232).

One ``skos:Concept`` per class the hub declares, linked to the ontology by
``skos:exactMatch`` and to the industry model by ``skos:broadMatch``, carrying the
canonical label and definition, the synonyms the business uses (from the discovery glossary
and the DDD overlay), the context-specific scope notes and examples (overlay), the source
names as hidden labels (bindings), and the Silver status as an editorial note. One
``skos:Collection`` per bounded context -- per domain when the hub has no DDD design yet.

**Generated, never hand-maintained.** A second, authored vocabulary drifts from the ontology
the moment it exists; the discovery glossary (DD-071) is honest about being inspiration for
that reason. This one is derived, so it is current by construction, and it lives in the
tracked ``architecture/ddd/`` lane beside the diagrams, regenerated by every
``project --target ddd``. It is emitted for every hub, DDD design or not: a domain design
already produces a language worth reading back to the SMEs.

Written to ``architecture/ddd/ubiquitous-language.ttl`` with a deterministic header (no
timestamp -- the lane is drift-gated).
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml
from rdflib import DCTERMS, RDFS, SKOS, Graph, Literal, Namespace, URIRef
from rdflib.namespace import OWL, RDF

from .ddd_context_projector import (
    STATUS_UNBOUND,
    ContextDomain,
    _collect,
    _label,
    _Model,
    _resolve_class_token,
)
from .shared import _toolkit_version, named_parents
from .uri_utils import extract_local_name

UBIQUITOUS_LANGUAGE_NAME = "ubiquitous-language.ttl"
GLOSSARY_SUBDIR = "businessdiscovery"

_GLOSSARY_LINKS = (RDFS.seeAlso, SKOS.relatedMatch, SKOS.exactMatch, SKOS.closeMatch)


@dataclass
class LanguageModel:
    """Everything the vocabulary and the concept guide say about the hub, collected once."""

    base: _Model
    domains: list[ContextDomain]
    hub_name: str
    terms_ns: str
    term_ids: dict[URIRef, str]
    sources: dict[URIRef, list[str]] = field(default_factory=dict)
    columns: dict[URIRef, dict[URIRef, list[tuple[str, str, str]]]] = field(default_factory=dict)
    bound_relationships: set[tuple[URIRef, URIRef]] = field(default_factory=set)
    glossary_alt: dict[URIRef, list[str]] = field(default_factory=dict)
    glossary_definitions: dict[URIRef, list[str]] = field(default_factory=dict)
    stale_glossary: list[tuple[str, str]] = field(default_factory=list)
    industry: dict[URIRef, list[URIRef]] = field(default_factory=dict)

    @property
    def graph(self) -> Graph:
        return self.base.graph

    def classes(self) -> list[URIRef]:
        return sorted(self.base.hub_classes, key=str)

    def groups(self) -> list[tuple[str, str, list[URIRef]]]:
        """``(id, label, classes)`` per bounded context, else per domain."""
        if self.base.contexts:
            grouped = self.base.by_context()
            return [
                (
                    "context-" + _sanitize(extract_local_name(str(ctx))),
                    _label(self.graph, ctx),
                    [cls for cls in grouped.get(ctx, []) if cls in self.base.hub_classes],
                )
                for ctx in self.base.contexts
            ]
        by_domain: dict[str, list[URIRef]] = {}
        for cls in self.classes():
            by_domain.setdefault(self.base.class_domain.get(cls, "hub"), []).append(cls)
        return [
            ("domain-" + _sanitize(name), name, classes)
            for name, classes in sorted(by_domain.items())
        ]

    def unassigned(self) -> list[URIRef]:
        if not self.base.contexts:
            return []
        return sorted((c for c in self.base.hub_classes if c not in self.base.context_of), key=str)


def _sanitize(text: str) -> str:
    return re.sub(r"[^0-9A-Za-z_]", "_", text)


def _terms_namespace(domains: list[ContextDomain], hub_name: str) -> str:
    """``<common prefix of the hub's ontology IRIs>terms#``, else a hub-named fallback.

    The common prefix of ``.../ontology/client`` and ``.../ontology/invoice`` is
    ``.../ontology/``; a single domain cuts back to its parent path. Only the domain file's
    own ``owl:Ontology`` counts, never an imported one.
    """
    iris: list[str] = []
    for domain in domains:
        graph = domain.local_graph if domain.local_graph is not None else domain.graph
        iris.extend(str(o) for o in graph.subjects(RDF.type, OWL.Ontology) if isinstance(o, URIRef))
    iris = sorted(set(iris))
    if iris:
        common = os.path.commonprefix(iris) if len(iris) > 1 else iris[0]
        cut = common.rfind("/")
        if cut > len("https://"):
            return common[: cut + 1] + "terms#"
    return f"https://kairos.cnext.eu/hubs/{_sanitize(hub_name).lower()}/terms#"


def _term_ids(model: _Model) -> dict[URIRef, str]:
    """One local id per hub class, suffixed with the domain when two share a local name."""
    by_name: dict[str, list[URIRef]] = {}
    for cls in sorted(model.hub_classes, key=str):
        by_name.setdefault(_sanitize(extract_local_name(str(cls))), []).append(cls)
    ids: dict[URIRef, str] = {}
    for name, claimants in by_name.items():
        if len(claimants) == 1:
            ids[claimants[0]] = name
            continue
        for cls in claimants:
            ids[cls] = f"{name}_{_sanitize(model.class_domain.get(cls, 'hub'))}"
    return ids


def _read_bindings(
    model: LanguageModel, bindings_dir: Optional[Path], by_name: dict[str, ContextDomain]
) -> None:
    """Source relations, mapped columns and realised relationships per class."""
    if bindings_dir is None or not Path(bindings_dir).is_dir():
        return
    for path in sorted(Path(bindings_dir).glob("*.yaml")):
        try:
            payload = yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001 - a malformed binding is the compiler's problem
            continue
        if not isinstance(payload, dict):
            continue
        metadata = payload.get("metadata") or {}
        domain = (
            by_name.get(str(metadata.get("domain") or "")) if isinstance(metadata, dict) else None
        )
        target = payload.get("target") or {}
        token = str(target.get("class") or "") if isinstance(target, dict) else ""
        iri = _resolve_class_token(domain, token)
        if iri is None:
            continue
        cls = URIRef(iri)
        source = payload.get("source") or {}
        relation = str(source.get("relation") or "") if isinstance(source, dict) else ""
        if relation:
            model.sources.setdefault(cls, [])
            if relation not in model.sources[cls]:
                model.sources[cls].append(relation)
        system, _, table = relation.partition(".")
        for item in payload.get("fields") or []:
            if not isinstance(item, dict):
                continue
            prop_iri = _resolve_class_token(domain, str(item.get("property") or ""))
            expression = item.get("expression")
            # Only a plain source-column expression is sampled; an operator or CASE tree
            # is a transformation, and a sample of its input is not a sample of its output.
            if prop_iri and isinstance(expression, str) and system and table:
                model.columns.setdefault(cls, {}).setdefault(URIRef(prop_iri), []).append(
                    (system, table, expression)
                )
        for item in payload.get("relationships") or []:
            if not isinstance(item, dict):
                continue
            prop_iri = _resolve_class_token(domain, str(item.get("property") or ""))
            if prop_iri:
                model.bound_relationships.add((cls, URIRef(prop_iri)))
    for values in model.sources.values():
        values.sort()


def _read_glossary(model: LanguageModel, glossary_dir: Optional[Path]) -> None:
    """Synonyms the discovery glossary attached to a hub class; stale links are reported."""
    if glossary_dir is None or not Path(glossary_dir).is_dir():
        return
    known = {s for s in model.graph.subjects(None, None) if isinstance(s, URIRef)}
    for path in sorted(Path(glossary_dir).glob("*-glossary.ttl")):
        if path.name.startswith("glossary-template"):
            continue
        glossary = Graph()
        try:
            glossary.parse(path, format="turtle")
        except Exception:  # noqa: BLE001 - the discovery gate reports glossary syntax
            continue
        for concept in sorted(set(glossary.subjects(RDF.type, SKOS.Concept)), key=str):
            links = sorted(
                {
                    o
                    for pred in _GLOSSARY_LINKS
                    for o in glossary.objects(concept, pred)
                    if isinstance(o, URIRef)
                },
                key=str,
            )
            labels = sorted(
                {str(lbl) for lbl in glossary.objects(concept, SKOS.altLabel)}
                | {str(lbl) for lbl in glossary.objects(concept, SKOS.prefLabel)}
            )
            definitions = sorted(str(d) for d in glossary.objects(concept, SKOS.definition))
            for linked in links:
                if linked in model.base.hub_classes:
                    canonical = _label(model.graph, linked)
                    alt = model.glossary_alt.setdefault(linked, [])
                    for label in labels:
                        if label != canonical and label not in alt:
                            alt.append(label)
                    defs = model.glossary_definitions.setdefault(linked, [])
                    for definition in definitions:
                        if definition not in defs:
                            defs.append(definition)
                elif linked not in known:
                    model.stale_glossary.append((str(concept), str(linked)))
    for alt in model.glossary_alt.values():
        alt.sort()
    model.stale_glossary.sort()


def build_language_model(
    domains: list[ContextDomain],
    *,
    strategic_path: Optional[Path] = None,
    contracts_dir: Optional[Path] = None,
    bindings_dir: Optional[Path] = None,
    hub_root: Optional[Path] = None,
    glossary_dir: Optional[Path] = None,
    hub_name: str = "hub",
) -> LanguageModel:
    """Collect once what both the vocabulary and the concept guide render."""
    base = _collect(domains, strategic_path, contracts_dir, bindings_dir, hub_root)
    model = LanguageModel(
        base=base,
        domains=domains,
        hub_name=hub_name,
        terms_ns=_terms_namespace(domains, hub_name),
        term_ids=_term_ids(base),
    )
    by_name = {domain.name: domain for domain in domains}
    _read_bindings(model, bindings_dir, by_name)
    if glossary_dir is None and hub_root is not None:
        glossary_dir = Path(hub_root) / GLOSSARY_SUBDIR
    _read_glossary(model, glossary_dir)
    for cls in model.classes():
        parents = [p for p in named_parents(base.graph, cls) if p not in base.hub_classes]
        if parents:
            model.industry[cls] = parents
    return model


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _pref_label(graph: Graph, cls: URIRef) -> Literal:
    value = graph.value(cls, RDFS.label)
    if isinstance(value, Literal):
        return Literal(str(value), lang=value.language or "en")
    return Literal(extract_local_name(str(cls)), lang="en")


def language_header(hub_name: str) -> str:
    """Deterministic Turtle header: which toolkit wrote it, never when (drift-gated lane)."""
    return "\n".join(
        [
            f"# Generated by kairos-ontology {_toolkit_version()} -- do not edit",
            f"# Ubiquitous language of {hub_name} (DD-232): one skos:Concept per hub class,",
            "# derived from the ontology, the DDD overlay, the discovery glossary and the",
            "# bindings. Regenerate with `kairos-ontology project --target ddd`.",
            "",
        ]
    )


def render_ubiquitous_language(model: LanguageModel) -> str:
    graph = Graph()
    terms = Namespace(model.terms_ns)
    graph.bind("skos", SKOS)
    graph.bind("rdfs", RDFS)
    graph.bind("dct", DCTERMS)
    graph.bind("terms", terms)

    scheme = URIRef(model.terms_ns.rstrip("#/"))
    graph.add((scheme, RDF.type, SKOS.ConceptScheme))
    graph.add((scheme, RDFS.label, Literal(f"{model.hub_name} ubiquitous language", lang="en")))
    graph.add(
        (
            scheme,
            DCTERMS.description,
            Literal(
                "Generated from the canonical ontology, its DDD overlay, the discovery glossary "
                "and the EntityBindings (DD-232). Derived, therefore current: never edit by hand."
            ),
        )
    )

    concepts: dict[URIRef, URIRef] = {}
    for cls in model.classes():
        concept = terms[model.term_ids[cls]]
        concepts[cls] = concept
        graph.add((concept, RDF.type, SKOS.Concept))
        graph.add((concept, SKOS.inScheme, scheme))
        graph.add((concept, SKOS.prefLabel, _pref_label(model.graph, cls)))
        comment = model.graph.value(cls, RDFS.comment)
        if comment is not None:
            graph.add((concept, SKOS.definition, Literal(str(comment))))
        for definition in model.glossary_definitions.get(cls, []):
            graph.add(
                (concept, SKOS.note, Literal(f"Business definition (discovery): {definition}"))
            )
        graph.add((concept, SKOS.exactMatch, cls))
        for parent in model.industry.get(cls, []):
            graph.add((concept, SKOS.broadMatch, parent))
        alt = set(model.base.alt_labels.get(cls, [])) | set(model.glossary_alt.get(cls, []))
        for label in sorted(alt):
            graph.add((concept, SKOS.altLabel, Literal(label, lang="en")))
        for note in model.base.scope_notes.get(cls, []):
            graph.add((concept, SKOS.scopeNote, Literal(note)))
        for example in model.base.examples.get(cls, []):
            graph.add((concept, SKOS.example, Literal(example)))
        for relation in model.sources.get(cls, []):
            graph.add((concept, SKOS.hiddenLabel, Literal(relation)))
        status = model.base.silver.get(cls, STATUS_UNBOUND)
        disposition = model.base.dispositions.get(cls)
        note = f"silver: {status}" + (f"; disposition: {disposition}" if disposition else "")
        graph.add((concept, SKOS.editorialNote, Literal(note)))

    for group_id, label, classes in model.groups():
        if not classes:
            continue
        collection = terms[group_id]
        graph.add((collection, RDF.type, SKOS.Collection))
        graph.add((collection, SKOS.inScheme, scheme))
        graph.add((collection, SKOS.prefLabel, Literal(label, lang="en")))
        for cls in classes:
            graph.add((collection, SKOS.member, concepts[cls]))

    body = graph.serialize(format="turtle")
    return language_header(model.hub_name) + body


def generate_ubiquitous_language(model: LanguageModel) -> dict[str, str]:
    """``{"ubiquitous-language.ttl": content}``; empty only when the hub declares no class."""
    if not model.base.hub_classes:
        return {}
    return {UBIQUITOUS_LANGUAGE_NAME: render_ubiquitous_language(model)}


def language_inputs(hub_root: Optional[Path]) -> dict[str, Any]:
    """The ``kairos.yaml`` switches for the language artifacts (samples default off)."""
    if hub_root is None:
        return {"samples": 0}
    from ..hub_config import load_hub_config

    section = load_hub_config(hub_root).get("projections")
    guide = section.get("concept_guide") if isinstance(section, dict) else None
    if not isinstance(guide, dict) or not guide.get("samples"):
        return {"samples": 0}
    raw = guide.get("max_samples", 3)
    try:
        return {"samples": max(0, int(raw))}
    except (TypeError, ValueError):
        return {"samples": 3}
