# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Provenance comment headers for toolkit-generated Turtle (DD-072).

When the toolkit deterministically writes a ``.ttl`` artifact (source vocabulary,
SKOS glossary, scaffold starter ontology) the file carries no trace of what
produced it.  This module emits a small, non-intrusive **Turtle comment header**
stamping the toolkit version, a UTC generation timestamp, the generator name and a
short edit-policy note.

The header is plain ``#`` comments prepended to the serialized Turtle: it adds no
RDF triples, so it never affects parsing, SHACL validation or projection logic
(``rdflib`` simply ignores comments when it re-parses a file).

The same helper is exposed so hand-authored ontology/SHACL files (written by the
design skills) can adopt the identical convention.
"""

from __future__ import annotations

from datetime import datetime, timezone

# Marker that delimits a toolkit-managed provenance block.  ``prepend_provenance``
# uses it to strip a previous header before stamping a fresh one, so regenerating a
# file never stacks multiple headers.
_MARKER = "kairos-ontology-toolkit"
_RULE = "# " + "-" * 70

_EDIT_NOTE_GENERATED = "Do not edit by hand — regenerate via the CLI/skill."
_EDIT_NOTE_EDITABLE = "Scaffolded starting point — safe to edit and extend."


def _toolkit_version() -> str:
    """Return the running toolkit version (lazy import avoids a cycle)."""
    try:
        from kairos_ontology import __version__

        return __version__
    except Exception:  # pragma: no cover - defensive only
        return "unknown"


def provenance_comment(
    generator: str,
    *,
    generated_at: datetime | None = None,
    editable: bool = False,
    extra: dict[str, str] | None = None,
) -> str:
    """Build a Turtle ``#``-comment provenance header.

    Args:
        generator: Short name of the producer (e.g. ``"build-glossary"``).
        generated_at: Generation time; defaults to ``datetime.now(timezone.utc)``.
            Inject a fixed value in tests for deterministic output.
        editable: ``True`` stamps a "safe to edit" note (scaffold starters);
            ``False`` (default) stamps a "do not edit — regenerate" note.
        extra: Optional ordered ``label -> value`` lines rendered after the header.

    Returns:
        The comment block as a string ending with a trailing newline.
    """
    ts = generated_at or datetime.now(timezone.utc)
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    ts = ts.astimezone(timezone.utc)
    stamp = ts.strftime("%Y-%m-%dT%H:%M:%SZ")
    note = _EDIT_NOTE_EDITABLE if editable else _EDIT_NOTE_GENERATED

    lines = [
        _RULE,
        f"# Generated by {_MARKER} v{_toolkit_version()}",
        f"# Generator : {generator}",
        f"# Generated : {stamp} (UTC)",
    ]
    for label, value in (extra or {}).items():
        lines.append(f"# {label} : {value}")
    lines.append(f"# {note}")
    lines.append(_RULE)
    return "\n".join(lines) + "\n"


def strip_provenance(ttl: str) -> str:
    """Remove a leading toolkit provenance header from *ttl*, if present.

    Only strips a block at the very top of the document delimited by the rule
    lines and containing the toolkit marker, so user comments are never touched.
    """
    lines = ttl.splitlines()
    if not lines or lines[0].strip() != _RULE:
        return ttl
    # Find the closing rule line of the header block.
    for idx in range(1, len(lines)):
        if lines[idx].strip() == _RULE:
            block = "\n".join(lines[: idx + 1])
            if _MARKER not in block:
                return ttl  # not our header — leave it alone
            rest = lines[idx + 1 :]
            # Drop a single blank separator line if present.
            if rest and rest[0].strip() == "":
                rest = rest[1:]
            return "\n".join(rest) + ("\n" if ttl.endswith("\n") else "")
    return ttl


def prepend_provenance(
    ttl: str,
    generator: str,
    *,
    generated_at: datetime | None = None,
    editable: bool = False,
    extra: dict[str, str] | None = None,
) -> str:
    """Return *ttl* with a fresh provenance header prepended.

    Idempotent: any existing toolkit header at the top of *ttl* is stripped first,
    so regenerating a file never stacks multiple headers.
    """
    header = provenance_comment(
        generator, generated_at=generated_at, editable=editable, extra=extra
    )
    body = strip_provenance(ttl).lstrip("\n")
    return f"{header}\n{body}"
