# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Scaffold first-class ``stg_<source>__<entity>`` + ``int_merged__<entity>`` staging.

Issue #399: ``kairos-develop-dbt-transformation/SKILL.md`` already documents this
layering in detail (per-source ``stg_*`` models feeding one ``int_merged__<entity>``
survivorship model, each independently owned/contracted/tested) but names it "a
convention, not an enforced or linted invariant" -- no command generates the files. This
module is the tooling half of that gap: it reuses :func:`scaffold_binding.render_staging_sql`
(the same per-table staging SELECT already used by ``scaffold-binding``'s passthrough
archetype) for each contributing source, then generates one merged survivorship model
with sentinel placeholders for the judgment a human/agent must confirm (natural key,
priority order, target class, virtual source identity) -- the same
``<CONFIRM_...>``-sentinel philosophy ``scaffold-binding`` already uses for grain and
identity, so ``compile --check`` rejects the merged model's contract until confirmed.

The ``target_class`` half of that claim was false until issue #503: nothing read
``meta.kairos.target_class`` at compile time, so ``<CONFIRM_TARGET_CLASS>`` passed
``compile --check`` unnoticed. ``compiler/dbt_source.py`` now requires it to be an absolute
HTTP(S) IRI and cross-checks it against the binding's resolved target class, and
``kairos-ontology validate-dbt-contracts`` reports every unreplaced sentinel by name without
needing a binding to exist at all.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .scaffold_binding import SourceColumn, load_table_columns, render_staging_sql

SENTINEL_TARGET_CLASS = "<CONFIRM_TARGET_CLASS>"
SENTINEL_VIRTUAL_SOURCE_IRI = "<CONFIRM_VIRTUAL_SOURCE_IRI>"
SENTINEL_GRAIN = "<CONFIRM_GRAIN_DESCRIPTION>"
SENTINEL_GRAIN_KEY = "<CONFIRM_GRAIN_KEY_COLUMN>"
SENTINEL_NATURAL_KEY = "<CONFIRM_NATURAL_KEY_COLUMN>"
SENTINEL_PRIORITY_COLUMN = "<CONFIRM_PRIORITY_COLUMN>"
SENTINEL_ADAPTER = "<CONFIRM_SUPPORTED_ADAPTER>"


class ScaffoldStagingError(ValueError):
    """Raised for a user-facing ``scaffold-staging`` failure (bad source, bad entity name)."""


@dataclass(frozen=True, slots=True)
class StageWritten:
    """One per-source ``stg_<source>__<entity>`` model and its properties YAML."""

    system: str
    table: str
    model_name: str
    sql_path: Path
    yaml_path: Path
    sql_written: bool
    yaml_written: bool
    columns: tuple[SourceColumn, ...]


@dataclass(frozen=True, slots=True)
class ScaffoldStagingResult:
    """Everything written (or, in dry-run, that would be written) for one entity."""

    entity: str
    domain: str
    stages: tuple[StageWritten, ...]
    merged_model_name: str
    merged_sql_path: Path
    merged_yaml_path: Path
    merged_sql_written: bool
    merged_yaml_written: bool
    common_columns: tuple[str, ...]
    notes: tuple[str, ...]


def _stage_properties_yaml(model_name: str, system: str, table: str, columns: tuple[SourceColumn, ...]) -> str:
    lines = [
        "version: 2",
        "models:",
        f"  - name: {model_name}",
        f'    description: "Cleaned per-source stage for {system}.{table} (scaffold-staging, issue #399)."',
        "    config:",
        "      materialized: view",
        "      contract:",
        "        enforced: true",
        "    columns:",
    ]
    for column in columns:
        lines.append(f"      - name: {column.name}")
        lines.append(f"        data_type: {column.data_type or 'string'}")
        if column.is_primary_key:
            lines.append("        data_tests: [not_null]")
    lines.append("      - name: source_system")
    lines.append("        data_type: string")
    lines.append("        data_tests: [not_null]")
    return "\n".join(lines) + "\n"


def _merged_sql(entity: str, stage_names: tuple[str, ...], common_columns: tuple[str, ...]) -> str:
    select_cols = list(common_columns) or ["/* no columns are common to every source stage */"]
    lines = [
        "-- MACHINE-GENERATED by kairos-ontology scaffold-staging (issue #399).",
        f"-- Survivorship union+rank for entity '{entity}' across {len(stage_names)} source stage(s).",
        "-- Review before productionizing:",
        f"--   - confirm the natural key ({SENTINEL_NATURAL_KEY}) and priority order",
        f"--     ({SENTINEL_PRIORITY_COLUMN}) below -- these are irreducible modeling judgment,",
        "--     not something this scaffold can infer.",
        "--   - only columns common to every source stage are selected below; add any",
        "--     source-specific or complementary-attribute columns by hand (see",
        "--     kairos-develop-dbt-transformation/SKILL.md's two reconciliation strategies --",
        "--     survivorship here, or attribute-level outer join if sources are complementary",
        "--     rather than competing).",
        "-- Materialization and contract enforcement are declared in this model's properties",
        "-- YAML (config.materialized/config.contract.enforced), matching every other",
        "-- contracted model in this project -- not duplicated here via an inline config().",
        "",
        "with unioned as (",
    ]
    for index, stage_name in enumerate(stage_names):
        lines.append("    select")
        for column in select_cols:
            lines.append(f"        {column},")
        lines.append("        source_system")
        lines.append(f"    from {{{{ ref('{stage_name}') }}}}")
        if index < len(stage_names) - 1:
            lines.append("    union all")
    lines.extend(
        [
            "),",
            "ranked as (",
            "    select",
            "        *,",
            "        {{ kairos_survivor(",
            f"            natural_key=['{SENTINEL_NATURAL_KEY}'],",
            f"            priority_column='{SENTINEL_PRIORITY_COLUMN}'",
            "        ) }} as _kairos_survivor_rank",
            "    from unioned",
            ")",
            "select *",
            "from ranked",
            "where _kairos_survivor_rank = 1",
            "",
        ]
    )
    return "\n".join(lines)


def _merged_properties_yaml(entity: str, common_columns: tuple[str, ...]) -> str:
    model_name = f"int_merged__{entity}"
    lines = [
        "version: 2",
        "models:",
        f"  - name: {model_name}",
        f'    description: "Merged survivorship model for {entity} (scaffold-staging, issue #399)."',
        "    config:",
        "      materialized: view",
        "      contract:",
        "        enforced: true",
        "    meta:",
        "      kairos:",
        f"        target_class: {SENTINEL_TARGET_CLASS}",
        f"        virtual_source_iri: {SENTINEL_VIRTUAL_SOURCE_IRI}",
        f"        grain: {SENTINEL_GRAIN}",
        f"        grain_key: [{SENTINEL_GRAIN_KEY}]",
        f"        supported_adapters: [{SENTINEL_ADAPTER}]",
        "    columns:",
    ]
    for name in common_columns:
        lines.append(f"      - name: {name}")
        lines.append("        data_type: string")
    lines.append("      - name: source_system")
    lines.append("        data_type: string")
    lines.append("        data_tests: [not_null]")
    return "\n".join(lines) + "\n"


def run_scaffold_staging(
    hub_root: Path,
    *,
    entity: str,
    domain: str,
    sources: tuple[tuple[str, str], ...],
    force: bool = False,
    dry_run: bool = False,
) -> ScaffoldStagingResult:
    """Scaffold one ``stg_<source>__<entity>`` model per *sources* entry, plus one merged model.

    *sources* is an ordered tuple of ``(system, table)`` pairs, each already registered
    under ``integration/sources/<system>/`` (the same evidence ``scaffold-binding`` reads).
    Never overwrites an existing file unless *force* is set; *dry_run* reports what would be
    written without writing anything.
    """
    if not entity or not entity.replace("_", "").isalnum():
        raise ScaffoldStagingError(f"--entity must be a plain identifier, got {entity!r}")
    if len(sources) < 2:
        raise ScaffoldStagingError(
            "scaffold-staging requires at least two --source entries; a single source "
            "does not need the merged layer (author a plain source.relation binding instead)"
        )

    models_dir = hub_root / "integration" / "transforms" / "dbt" / "models" / "intermediate" / domain
    notes: list[str] = []
    stages: list[StageWritten] = []
    column_sets: list[set[str]] = []
    columns_by_name: dict[str, SourceColumn] = {}

    for system, table in sources:
        columns = load_table_columns(hub_root, system, table)
        column_sets.append({column.name for column in columns})
        for column in columns:
            columns_by_name.setdefault(column.name, column)
        model_name = f"stg_{system}__{entity}"
        sql_path = models_dir / f"{model_name}.sql"
        yaml_path = models_dir / f"{model_name}.yml"
        sql_text = render_staging_sql(system, table, columns)
        yaml_text = _stage_properties_yaml(model_name, system, table, columns)

        sql_written = False
        if sql_path.is_file() and not force:
            notes.append(f"{sql_path} already exists; not overwritten (pass --force).")
        elif dry_run:
            notes.append(f"dry-run: {sql_path} was not written.")
        else:
            sql_path.parent.mkdir(parents=True, exist_ok=True)
            sql_path.write_text(sql_text, encoding="utf-8")
            sql_written = True

        yaml_written = False
        if yaml_path.is_file() and not force:
            notes.append(f"{yaml_path} already exists; not overwritten (pass --force).")
        elif dry_run:
            notes.append(f"dry-run: {yaml_path} was not written.")
        else:
            yaml_path.parent.mkdir(parents=True, exist_ok=True)
            yaml_path.write_text(yaml_text, encoding="utf-8")
            yaml_written = True

        stages.append(
            StageWritten(
                system=system,
                table=table,
                model_name=model_name,
                sql_path=sql_path,
                yaml_path=yaml_path,
                sql_written=sql_written,
                yaml_written=yaml_written,
                columns=columns,
            )
        )

    common_columns = tuple(
        sorted(set.intersection(*column_sets)) if column_sets else ()
    )
    if not common_columns:
        notes.append(
            "no column name is common to every source stage; the merged model's SELECT "
            "was scaffolded with no columns beyond source_system -- author the union "
            "(or attribute-level outer join) by hand."
        )

    merged_model_name = f"int_merged__{entity}"
    merged_sql_path = models_dir / f"{merged_model_name}.sql"
    merged_yaml_path = models_dir / f"{merged_model_name}.yml"
    stage_names = tuple(stage.model_name for stage in stages)
    merged_sql_text = _merged_sql(entity, stage_names, common_columns)
    merged_yaml_text = _merged_properties_yaml(entity, common_columns)

    merged_sql_written = False
    if merged_sql_path.is_file() and not force:
        notes.append(f"{merged_sql_path} already exists; not overwritten (pass --force).")
    elif dry_run:
        notes.append(f"dry-run: {merged_sql_path} was not written.")
    else:
        merged_sql_path.parent.mkdir(parents=True, exist_ok=True)
        merged_sql_path.write_text(merged_sql_text, encoding="utf-8")
        merged_sql_written = True

    merged_yaml_written = False
    if merged_yaml_path.is_file() and not force:
        notes.append(f"{merged_yaml_path} already exists; not overwritten (pass --force).")
    elif dry_run:
        notes.append(f"dry-run: {merged_yaml_path} was not written.")
    else:
        merged_yaml_path.parent.mkdir(parents=True, exist_ok=True)
        merged_yaml_path.write_text(merged_yaml_text, encoding="utf-8")
        merged_yaml_written = True

    return ScaffoldStagingResult(
        entity=entity,
        domain=domain,
        stages=tuple(stages),
        merged_model_name=merged_model_name,
        merged_sql_path=merged_sql_path,
        merged_yaml_path=merged_yaml_path,
        merged_sql_written=merged_sql_written,
        merged_yaml_written=merged_yaml_written,
        common_columns=common_columns,
        notes=tuple(notes),
    )
