-- Kairos Boolean macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware boolean literal.
-- Fabric/T-SQL: 1/0 (BIT)
-- Snowflake/Databricks: TRUE/FALSE

{% macro kairos_bool(value) -%}
  {%- if target.type == 'fabric' -%}
    {%- if value -%}1{%- else -%}0{%- endif -%}
  {%- else -%}
    {%- if value -%}TRUE{%- else -%}FALSE{%- endif -%}
  {%- endif -%}
{%- endmacro %}
