-- Kairos Date Spine macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware date spine generator for dim_date models.
-- Returns a series of integers (0 to row_count-1) that can be used with
-- DATEADD to generate date ranges.
-- Fabric/T-SQL: GENERATE_SERIES(0, N-1) with DATEADD
-- Snowflake: TABLE(GENERATOR(ROWCOUNT => N)) with ROW_NUMBER

{% macro kairos_date_spine(row_count) -%}
  {%- if target.type == 'fabric' -%}
    (SELECT DATEADD(day, value, CAST('2000-01-01' AS DATE)) AS value
     FROM GENERATE_SERIES(0, {{ row_count - 1 }}))
  {%- else -%}
    (SELECT DATEADD(day, ROW_NUMBER() OVER (ORDER BY NULL) - 1,
                    '2000-01-01'::DATE) AS value
     FROM TABLE(GENERATOR(ROWCOUNT => {{ row_count }})))
  {%- endif -%}
{%- endmacro %}
