-- Kairos Normalize Key macro
-- Generated by Kairos Ontology Toolkit
--
-- Args:
--   column: SQL expression or column reference containing a natural key.
-- Behavior: returns the canonical natural-key form upper(trim(column)) and maps the
-- empty-string result to NULL so blank keys do not collide. Collation and Unicode
-- folding are not applied.
-- Fabric/T-SQL: NULLIF(upper(trim(column)), '')
-- Databricks/Spark: NULLIF(upper(trim(column)), '')

{% macro kairos_normalize_key(column) -%}
  NULLIF(upper(trim({{ column }})), '')
{%- endmacro %}
