-- Kairos Source System Label macro
-- Generated by Kairos Ontology Toolkit
--
-- Args:
--   column: SQL expression or column reference containing a source-system code.
-- Behavior: returns a human-readable source-system label. The default implementation is
-- a trimmed passthrough; hubs may wrap or replace upstream values before calling this
-- macro when a governed code-to-label mapping is needed.
-- Fabric/T-SQL: trim(column)
-- Databricks/Spark: trim(column)

{% macro kairos_source_system_label(column) -%}
  trim({{ column }})
{%- endmacro %}
