-- Kairos Survivor macro
-- Generated by Kairos Ontology Toolkit
--
-- Args:
--   natural_key: list of SQL expressions that define the survivor partition.
--   priority_column: SQL expression sorted ascending; defaults to source_priority.
--   tiebreak: optional list of SQL expressions appended to ORDER BY.
-- Behavior: emits row_number() over (...) for callers to filter with = 1. Callers must
-- provide a mandatory total order through priority_column plus deterministic tiebreaks.
-- Fabric/T-SQL: row_number() over (partition by ... order by ... asc, ...)
-- Databricks/Spark: row_number() over (partition by ... order by ... asc, ...)

{% macro kairos_survivor(natural_key, priority_column='source_priority', tiebreak=[]) -%}
  row_number() over (
    partition by {{ natural_key | join(', ') }}
    order by {{ priority_column }} asc{% for expression in tiebreak %}, {{ expression }}{% endfor %}
  )
{%- endmacro %}
