-- Kairos JSON extraction macros
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware JSON value extraction for single values.
-- For array expansion (OPENJSON / EXPLODE), use the platform-specific staging template.

{% macro kairos_json_value(column, json_path) -%}
    {%- if target.type == 'fabric' -%}
        JSON_VALUE({{ column }}, '{{ json_path }}')
    {%- elif target.type in ('spark', 'databricks') -%}
        GET_JSON_OBJECT({{ column }}, '{{ json_path }}')
    {%- else -%}
        JSON_VALUE({{ column }}, '{{ json_path }}')
    {%- endif -%}
{%- endmacro %}


{% macro kairos_json_array_length(column) -%}
    {%- if target.type == 'fabric' -%}
        (SELECT COUNT(*) FROM OPENJSON({{ column }}))
    {%- elif target.type in ('spark', 'databricks') -%}
        SIZE(FROM_JSON({{ column }}, 'array<string>'))
    {%- else -%}
        JSON_ARRAY_LENGTH({{ column }})
    {%- endif -%}
{%- endmacro %}
