-- Kairos Clean Sentinel macro
-- Generated by Kairos Ontology Toolkit
--
-- Args:
--   column: SQL expression or column reference to clean.
--   sentinels: string values that represent missing data; defaults to ['-'].
-- Behavior: maps each sentinel to NULL with nested NULLIF calls, preserving existing NULLs
-- and all non-sentinel values.
-- Fabric/T-SQL: NULLIF(NULLIF(column, '-'), ...)
-- Databricks/Spark: NULLIF(NULLIF(column, '-'), ...)

{% macro kairos_clean_sentinel(column, sentinels=['-']) -%}
  {%- set ns = namespace(expr=column) -%}
  {%- for sentinel in sentinels -%}
    {%- set literal = "'" ~ (sentinel | replace("'", "''")) ~ "'" -%}
    {%- set ns.expr = "NULLIF(" ~ ns.expr ~ ", " ~ literal ~ ")" -%}
  {%- endfor -%}
  {{ ns.expr }}
{%- endmacro %}
