-- DD-109 runtime contract tests generated by Kairos Ontology Toolkit.

{% macro test_kairos_runtime_total_order(model, identity_columns, ordering_columns) %}
select
{%- for column in identity_columns + ordering_columns %}
    {{ adapter.quote(column) }}{% if not loop.last %},{% endif %}
{%- endfor %},
    count(*) as duplicate_count
from {{ model }}
group by
{%- for column in identity_columns + ordering_columns %}
    {{ adapter.quote(column) }}{% if not loop.last %},{% endif %}
{%- endfor %}
having count(*) > 1
{% endmacro %}

{% macro test_kairos_runtime_cdc_contract(
    model,
    operation_column,
    source_updated_at,
    source_effective_at,
    ingested_at
) %}
select *
from {{ model }}
where {{ adapter.quote(operation_column) }}
        not in ('insert', 'update', 'delete', 'soft-delete', 'snapshot')
   or {{ adapter.quote(source_updated_at) }} is null
   or {{ adapter.quote(source_effective_at) }} is null
   or {{ adapter.quote(ingested_at) }} is null
{% endmacro %}

{% macro test_kairos_runtime_delete_policy(
    model,
    operation_column,
    hard_action,
    soft_action
) %}
select *
from {{ model }}
where ('{{ hard_action }}' = 'block'
       and {{ adapter.quote(operation_column) }} = 'delete')
   or ('{{ soft_action }}' = 'block'
       and {{ adapter.quote(operation_column) }} = 'soft-delete')
{% endmacro %}

{% macro test_kairos_runtime_replay_idempotent(
    model,
    identity_columns,
    operation_column
) %}
select
{%- for column in identity_columns %}
    {{ adapter.quote(column) }},
{%- endfor %}
    {{ adapter.quote(operation_column) }},
    _source_effective_at,
    _source_updated_at,
    _ingested_at,
    count(*) as replay_count
from {{ model }}
group by
{%- for column in identity_columns %}
    {{ adapter.quote(column) }},
{%- endfor %}
    {{ adapter.quote(operation_column) }},
    _source_effective_at,
    _source_updated_at,
    _ingested_at
having count(*) > 1
{% endmacro %}

{% macro test_kairos_runtime_one_current(model, identity_columns, current_column) %}
select
{%- for column in identity_columns %}
    {{ adapter.quote(column) }}{% if not loop.last %},{% endif %}
{%- endfor %},
    sum(case when {{ adapter.quote(current_column) }} = 1 then 1 else 0 end)
      as current_count
from {{ model }}
group by
{%- for column in identity_columns %}
    {{ adapter.quote(column) }}{% if not loop.last %},{% endif %}
{%- endfor %}
having sum(case when {{ adapter.quote(current_column) }} = 1 then 1 else 0 end) <> 1
{% endmacro %}

{% macro test_kairos_runtime_half_open_intervals(
    model,
    identity_columns,
    business_from_column,
    business_to_column,
    system_from_column,
    system_to_column
) %}
with ordered as (
    select
        *,
        lag({{ adapter.quote(business_to_column) }}) over (
            partition by
{%- for column in identity_columns %}
                {{ adapter.quote(column) }}{% if not loop.last %},{% endif %}
{%- endfor %}
            order by {{ adapter.quote(business_from_column) }},
                {{ adapter.quote(system_from_column) }}
        ) as _previous_business_to,
        lag({{ adapter.quote(system_to_column) }}) over (
            partition by
{%- for column in identity_columns %}
                {{ adapter.quote(column) }}{% if not loop.last %},{% endif %}
{%- endfor %}
            order by {{ adapter.quote(system_from_column) }}
        ) as _previous_system_to
    from {{ model }}
)
select *
from ordered
where (
        {{ adapter.quote(business_to_column) }} is not null
        and {{ adapter.quote(business_from_column) }}
          >= {{ adapter.quote(business_to_column) }}
    )
    or (
        {{ adapter.quote(system_to_column) }} is not null
        and {{ adapter.quote(system_from_column) }}
          >= {{ adapter.quote(system_to_column) }}
    )
    or (
        _previous_business_to is not null
        and {{ adapter.quote(business_from_column) }} < _previous_business_to
    )
    or (
        _previous_system_to is not null
        and {{ adapter.quote(system_from_column) }} < _previous_system_to
    )
{% endmacro %}

{% macro test_kairos_temporal_fk_cardinality(
    model,
    property_uri,
    match_count_column,
    mode,
    cardinality,
    missing_action,
    ambiguous_action
) %}
select *
from {{ model }}
where {{ adapter.quote(match_count_column) }} > 1
{%- if (
    cardinality == "exactly-one" or missing_action == "fail"
  ) and missing_action != "unknown-member" %}
    or {{ adapter.quote(match_count_column) }} = 0
{%- endif %}
{% endmacro %}
