-- Kairos String Concat macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware string concatenation.

{% macro kairos_concat() -%}
    {%- if target.type == 'fabric' -%}
        CONCAT({{ varargs | join(', ') }})
    {%- elif target.type in ('spark', 'databricks') -%}
        CONCAT({{ varargs | join(', ') }})
    {%- else -%}
        CONCAT({{ varargs | join(', ') }})
    {%- endif -%}
{%- endmacro %}
