-- Kairos Row Hash macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware row hashing for SCD2 change detection.
-- Fabric/T-SQL: HASHBYTES('SHA2_256', ...) returns binary → CONVERT to hex.
-- Snowflake/Databricks: SHA2_HEX(CONCAT_WS(...)).

{% macro kairos_row_hash(columns) -%}
  {%- if target.type == 'fabric' -%}
    CONVERT(VARCHAR(64), HASHBYTES('SHA2_256', CONCAT_WS('|'
      {%- for col in columns %}, COALESCE(CAST({{ col }} AS VARCHAR(4000)), ''){% endfor %}
    {%- if columns | length < 2 %}, ''{% endif %})), 2)
  {%- else -%}
    SHA2_HEX(CONCAT_WS('|'
      {%- for col in columns %}, COALESCE(CAST({{ col }} AS VARCHAR), ''){% endfor %}))
  {%- endif -%}
{%- endmacro %}
