-- Kairos Safe Cast macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware safe casting. Currently TRY_CAST works on both Fabric and
-- Databricks (Spark 3.4+). This macro exists for future-proofing (e.g., Snowflake
-- would need TRY_TO_CAST, PostgreSQL needs a custom function).

{% macro kairos_safe_cast(column, target_type) -%}
    {%- if target.type == 'fabric' -%}
        TRY_CAST({{ column }} AS {{ target_type }})
    {%- elif target.type in ('spark', 'databricks') -%}
        TRY_CAST({{ column }} AS {{ target_type }})
    {%- else -%}
        CAST({{ column }} AS {{ target_type }})
    {%- endif -%}
{%- endmacro %}
