-- Kairos Surrogate Key macro
-- Generated by Kairos Ontology Toolkit
--
-- Thin wrapper around dbt_utils.generate_surrogate_key().
-- Exists to allow future override (e.g., deterministic UUIDs, different hashing).

{% macro kairos_surrogate_key(field_list) -%}
    {{ dbt_utils.generate_surrogate_key(field_list) }}
{%- endmacro %}
