-- Kairos Date Part macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware date function dispatch for dim_date generation.
-- Fabric/T-SQL: DATEPART(weekday, col), DATENAME(month, col)
-- Snowflake: DAYOFWEEK(col), MONTHNAME(col)
-- Databricks: DAYOFWEEK(col), DATE_FORMAT(col, 'MMMM')

{% macro kairos_day_of_week(col) -%}
  {%- if target.type == 'fabric' -%}
    DATEPART(weekday, {{ col }})
  {%- else -%}
    DAYOFWEEK({{ col }})
  {%- endif -%}
{%- endmacro %}

{% macro kairos_month_name(col) -%}
  {%- if target.type == 'fabric' -%}
    CAST(DATENAME(month, {{ col }}) AS VARCHAR(30))
  {%- elif target.type in ('spark', 'databricks') -%}
    DATE_FORMAT({{ col }}, 'MMMM')
  {%- else -%}
    MONTHNAME({{ col }})
  {%- endif -%}
{%- endmacro %}

{% macro kairos_quarter(col) -%}
  {%- if target.type == 'fabric' -%}
    DATEPART(quarter, {{ col }})
  {%- else -%}
    QUARTER({{ col }})
  {%- endif -%}
{%- endmacro %}
