-- Kairos Current Date macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware current date expression.
-- Fabric/T-SQL: CAST(GETDATE() AS DATE)
-- Snowflake/Databricks: CURRENT_DATE (ANSI)

{% macro kairos_current_date() -%}
  {%- if target.type == 'fabric' -%}
    CAST(GETDATE() AS DATE)
  {%- else -%}
    CURRENT_DATE
  {%- endif -%}
{%- endmacro %}
