-- Kairos Quote Identifier macro
-- Generated by Kairos Ontology Toolkit
--
-- Platform-aware identifier quoting for reserved keywords.
-- Fabric/T-SQL: [identifier]
-- Databricks/Spark: `identifier`
-- Snowflake: "identifier"

{% macro kairos_quote_identifier(name) -%}
  {%- if target.type == 'fabric' -%}
    [{{ name }}]
  {%- elif target.type in ('spark', 'databricks') -%}
    `{{ name }}`
  {%- else -%}
    "{{ name }}"
  {%- endif -%}
{%- endmacro %}
