-- Kairos Current Timestamp macro
-- Generated by Kairos Ontology Toolkit
--
-- Sub-day SCD2 precision for Fabric and Databricks.

{% macro kairos_current_timestamp() -%}
  {%- if target.type == 'fabric' -%}
    CAST(GETDATE() AS DATETIME2(6))
  {%- else -%}
    CURRENT_TIMESTAMP
  {%- endif -%}
{%- endmacro %}
