# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Generate bronze_expanded staging models from extract-schema JSON metadata.

Reads per-table YAML files (v1.1) and generates dbt SQL models that flatten
JSON columns into typed columnar tables for the bronze_expanded layer.
"""

from __future__ import annotations

import logging
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)


def generate_staging_models(
    schema_dir: Path,
    output_dir: Path,
    source_name: str | None = None,
) -> list[Path]:
    """Generate dbt staging models for JSON flattening.

    Args:
        schema_dir: Directory with _manifest.yaml + per-table YAML (from extract-schema).
        output_dir: Where to write generated .sql models (e.g., models/staging/).
        source_name: dbt source name for {{ source() }} refs (default: from manifest).

    Returns:
        List of generated model file paths.
    """
    manifest_path = schema_dir / "_manifest.yaml"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"Missing _manifest.yaml in: {schema_dir}")

    with open(manifest_path, encoding="utf-8") as f:
        manifest = yaml.safe_load(f)

    system = source_name or manifest.get("system", "source")
    table_names = manifest.get("tables", [])

    output_dir.mkdir(parents=True, exist_ok=True)
    generated: list[Path] = []

    for tbl_name in table_names:
        tbl_path = schema_dir / f"{tbl_name}.yaml"
        if not tbl_path.is_file():
            continue

        with open(tbl_path, encoding="utf-8") as f:
            tbl_data = yaml.safe_load(f)

        if not tbl_data:
            continue

        models = _generate_models_for_table(tbl_data, system)
        for model_name, sql_content in models:
            model_path = output_dir / f"{model_name}.sql"
            model_path.write_text(sql_content, encoding="utf-8")
            generated.append(model_path)
            logger.info(f"Generated: {model_path}")

    return generated


def _generate_models_for_table(
    tbl_data: dict, source_name: str
) -> list[tuple[str, str]]:
    """Generate staging model(s) for a single table based on JSON columns.

    Returns list of (model_name, sql_content) tuples.
    """
    tbl_name = tbl_data.get("name", "unknown")
    columns = tbl_data.get("columns", [])
    models: list[tuple[str, str]] = []

    for col in columns:
        if not col.get("json_detected"):
            continue

        classification = col.get("json_classification", "")
        json_structure = col.get("json_structure", [])
        col_name = col.get("name", "")

        if not json_structure:
            continue

        if classification in ("flat", "nested"):
            model = _generate_flat_expansion(
                tbl_name, col_name, json_structure, source_name
            )
            if model:
                models.append(model)

        elif classification == "array_object":
            model = _generate_array_expansion(
                tbl_name, col_name, json_structure, source_name
            )
            if model:
                models.append(model)

    return models


def _generate_flat_expansion(
    tbl_name: str, col_name: str, json_structure: list[dict], source_name: str
) -> tuple[str, str] | None:
    """Generate a view that expands flat JSON keys into columns."""
    if not json_structure:
        return None

    model_name = f"stg_{source_name}_{tbl_name}_{col_name}"

    # Build JSON_VALUE expressions
    extractions = []
    for js in json_structure:
        key = js.get("key", "")
        js_type = js.get("type", "string")
        if not key:
            continue
        sql_type = _json_type_to_sql_cast(js_type)
        if sql_type:
            extractions.append(
                f"    CAST(JSON_VALUE([{col_name}], '$.{key}') AS {sql_type}) AS [{key}]"
            )
        else:
            extractions.append(
                f"    JSON_VALUE([{col_name}], '$.{key}') AS [{key}]"
            )

    if not extractions:
        return None

    # Find non-JSON columns to carry through (first few identity columns)
    sql = f"""-- Auto-generated by kairos-ontology extract-schema
-- Expands flat JSON column [{col_name}] from {tbl_name}
{{{{
  config(
    materialized='view',
    schema='bronze_expanded'
  )
}}}}
SELECT
    *,
{chr(10).join(f"{e}," for e in extractions[:-1])}
{extractions[-1]}
FROM {{{{ source('{source_name}', '{tbl_name}') }}}}
FROM {{{{ source('{source_name}', '{tbl_name}') }}}}
"""

    return (model_name, sql)


def _generate_array_expansion(
    tbl_name: str, col_name: str, json_structure: list[dict], source_name: str
) -> tuple[str, str] | None:
    """Generate a table that unpacks JSON array of objects via CROSS APPLY."""
    if not json_structure:
        return None

    model_name = f"stg_{source_name}_{tbl_name}_{col_name}"

    # Build JSON_VALUE expressions for each key in the array objects
    extractions = []
    for js in json_structure:
        key = js.get("key", "")
        js_type = js.get("type", "string")
        if not key:
            continue
        sql_type = _json_type_to_sql_cast(js_type)
        if sql_type:
            extractions.append(
                f"    CAST(JSON_VALUE(j.value, '$.{key}') AS {sql_type}) AS [{key}]"
            )
        else:
            extractions.append(
                f"    JSON_VALUE(j.value, '$.{key}') AS [{key}]"
            )

    if not extractions:
        return None

    sql = f"""-- Auto-generated by kairos-ontology extract-schema
-- Unpacks JSON array column [{col_name}] from {tbl_name}
{{{{
  config(
    materialized='table',
    schema='bronze_expanded'
  )
}}}}

SELECT
    src.*,
    j.[key] AS [{col_name}_index],
{chr(10).join(f"{e}," for e in extractions[:-1])}
{extractions[-1]}
FROM {{{{ source('{source_name}', '{tbl_name}') }}}} AS src
CROSS APPLY OPENJSON(src.[{col_name}]) AS j
WHERE src.[{col_name}] IS NOT NULL
"""

    return (model_name, sql)


def _json_type_to_sql_cast(json_type: str) -> str | None:
    """Map JSON type to SQL CAST type. Returns None for varchar (no cast needed)."""
    mapping = {
        "integer": "INT",
        "number": "DECIMAL(18,4)",
        "boolean": "BIT",
    }
    return mapping.get(json_type)
