# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Deterministic, byte-free five-phase dbt projection pipeline (DD-110).

The dbt projector is decomposed into explicit, ordered phases that exchange typed,
immutable intermediate models (see :mod:`.context`):

``bind → normalize → shape → materialize → render``

The public entrypoint ``generate_dbt_artifacts`` is a thin orchestrator. Bind consumes
RDF and authoring files, normalize classifies policy, shape emits logical specs,
materialize selects physical plans, and only render creates artifact content.
"""

from __future__ import annotations

from .bind import bind_sources
from .context import (
    BoundSources,
    DbtInputs,
    MaterializationPlan,
    ProjectionContract,
    ShapedProject,
)
from .diagnostics import (
    Diagnostic,
    DiagnosticCollector,
    DiagnosticFailure,
    DiagnosticSeverity,
    EvaluationResult,
    EvaluationStatus,
    ExecutionMode,
    Prerequisite,
    order_diagnostics,
)
from .materialize import collect_materialization, plan_materialization
from .mapping_normalize import normalize_mapping_expression
from .mapping_specs import (
    CaseExpression,
    ColumnMappingSpec,
    FunctionExpression,
    LiteralExpression,
    MacroExpression,
    MappingCapability,
    MappingContractError,
    MappingContractSpec,
    MappingExpressionMetadata,
    MappingNullPolicy,
    MappingRoute,
    NullExpression,
    OperatorExpression,
    SourceColumnExpression,
    TableMappingSpec,
)
from .normalize import normalize_contract
from .render import render_canonical_project, render_project
from .shape import shape_project
from .capabilities import ADAPTER_CAPABILITY_REGISTRY, negotiate_capabilities
from .canonical_hash import (
    CANONICAL_HASH_V1_GOLDEN_VECTORS,
    CanonicalHashError,
    CanonicalHashSqlInput,
    CanonicalValue,
    canonical_hash_v1,
    canonical_serialize_v1,
    render_canonical_hash_sql_v1,
)
from .gold_materialize import materialize_gold_product
from .gold_render import (
    gold_product_report,
    render_gold_dbt_artifacts,
    render_powerbi_artifacts,
)
from .gold_shape import shape_gold_product
from .gold_specs import (
    DimensionalGoldSpec,
    GoldCalendarRoleSpec,
    GoldCalendarSpec,
    GoldColumnSpec,
    GoldContractError,
    GoldMeasureSpec,
    GoldPhysicalColumnPlan,
    GoldPhysicalPlan,
    GoldPhysicalTablePlan,
    GoldProductLogicalSpec,
    GoldProductPhysicalSpec,
    GoldRelationshipSpec,
    GoldSecurityBindingSpec,
    GoldSecurityKind,
    GoldSecuritySpec,
    GoldTableSpec,
)
from .policy_normalize import (
    PolicyCollectionError,
    PolicyNormalizationError,
    PolicyNormalizationStages,
    normalize_medallion_policy,
)
from .policy_specs import (
    AdapterCapability,
    AdapterCapabilityRegistry,
    AdapterEvidenceSpec,
    AdapterName,
    CapabilityDisposition,
    CapabilityResultSpec,
    CanonicalHashPolicySpec,
    ContributionLineageRelationSpec,
    DataQualityRuleSpec,
    DqAction,
    DqCategory,
    DqCheckKind,
    DqResultStatus,
    DqRuntimeResultContractSpec,
    EntityIdentitySpec,
    IdentityRoleSpec,
    IdentityStrategy,
    GoldProductSpec,
    HistorySpec,
    IncrementalPolicySpec,
    MedallionPolicyFacts,
    MedallionPolicySpec,
    MultiSourcePolicySpec,
    PolicyIssue,
    SilverModelAuthoritySpec,
    SilverRuntimeAuthoritySpec,
    TemporalRelationshipSpec,
    TimestampSemanticSpec,
    TimestampSourceSpec,
)
from .runtime_reference import (
    RuntimeEvent,
    RuntimeSemanticsError,
    RuntimeVersion,
    bounded_lookback,
    deduplicate_replay,
    materialize_scd1,
    materialize_scd2,
    range_replay,
)
from .specs import (
    ColumnSpec,
    CoverageSpec,
    DqModelPhysicalPlan,
    DqRulePhysicalPlan,
    ForeignKeyPolicy,
    ModelIdentity,
    ModelOutcome,
    SchemaDocumentSpec,
    SchemaModelSpec,
    SilverModelOutcome,
    SilverForeignKeySpec,
    SilverKeySpec,
    SilverModelPhysicalPlan,
    SilverModelSpec,
    SilverPhysicalPlan,
    SilverRegistry,
)

__all__ = [
    "BoundSources",
    "ADAPTER_CAPABILITY_REGISTRY",
    "AdapterCapability",
    "AdapterCapabilityRegistry",
    "AdapterEvidenceSpec",
    "AdapterName",
    "CapabilityDisposition",
    "CapabilityResultSpec",
    "CanonicalHashPolicySpec",
    "CANONICAL_HASH_V1_GOLDEN_VECTORS",
    "CanonicalHashError",
    "CanonicalHashSqlInput",
    "CanonicalValue",
    "ContributionLineageRelationSpec",
    "CaseExpression",
    "ColumnSpec",
    "ColumnMappingSpec",
    "CoverageSpec",
    "DbtInputs",
    "DataQualityRuleSpec",
    "DqAction",
    "DqCategory",
    "DqCheckKind",
    "DqModelPhysicalPlan",
    "DqResultStatus",
    "DqRulePhysicalPlan",
    "DqRuntimeResultContractSpec",
    "EntityIdentitySpec",
    "EvaluationResult",
    "EvaluationStatus",
    "ExecutionMode",
    "IdentityRoleSpec",
    "IdentityStrategy",
    "ForeignKeyPolicy",
    "FunctionExpression",
    "GoldProductSpec",
    "DimensionalGoldSpec",
    "Diagnostic",
    "DiagnosticCollector",
    "DiagnosticFailure",
    "DiagnosticSeverity",
    "GoldCalendarRoleSpec",
    "GoldCalendarSpec",
    "GoldColumnSpec",
    "GoldContractError",
    "GoldMeasureSpec",
    "GoldPhysicalColumnPlan",
    "GoldPhysicalPlan",
    "GoldPhysicalTablePlan",
    "GoldProductLogicalSpec",
    "GoldProductPhysicalSpec",
    "GoldRelationshipSpec",
    "GoldSecurityBindingSpec",
    "GoldSecurityKind",
    "GoldSecuritySpec",
    "GoldTableSpec",
    "HistorySpec",
    "IncrementalPolicySpec",
    "LiteralExpression",
    "MacroExpression",
    "MappingCapability",
    "MappingContractError",
    "MappingContractSpec",
    "MappingExpressionMetadata",
    "MappingNullPolicy",
    "MappingRoute",
    "MaterializationPlan",
    "ModelIdentity",
    "ModelOutcome",
    "NullExpression",
    "OperatorExpression",
    "MedallionPolicyFacts",
    "MedallionPolicySpec",
    "MultiSourcePolicySpec",
    "PolicyNormalizationError",
    "PolicyCollectionError",
    "PolicyNormalizationStages",
    "PolicyIssue",
    "Prerequisite",
    "ProjectionContract",
    "SchemaDocumentSpec",
    "SchemaModelSpec",
    "ShapedProject",
    "SilverModelOutcome",
    "SilverForeignKeySpec",
    "SilverKeySpec",
    "SilverModelPhysicalPlan",
    "SilverModelSpec",
    "SilverPhysicalPlan",
    "order_diagnostics",
    "SilverModelAuthoritySpec",
    "SilverRuntimeAuthoritySpec",
    "SilverRegistry",
    "SourceColumnExpression",
    "TableMappingSpec",
    "TemporalRelationshipSpec",
    "TimestampSemanticSpec",
    "TimestampSourceSpec",
    "RuntimeEvent",
    "RuntimeSemanticsError",
    "RuntimeVersion",
    "bind_sources",
    "bounded_lookback",
    "canonical_hash_v1",
    "canonical_serialize_v1",
    "deduplicate_replay",
    "materialize_scd1",
    "materialize_scd2",
    "materialize_gold_product",
    "normalize_contract",
    "normalize_mapping_expression",
    "normalize_medallion_policy",
    "negotiate_capabilities",
    "plan_materialization",
    "collect_materialization",
    "render_project",
    "render_canonical_project",
    "render_gold_dbt_artifacts",
    "render_powerbi_artifacts",
    "gold_product_report",
    "render_canonical_hash_sql_v1",
    "range_replay",
    "shape_project",
    "shape_gold_product",
]
