#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
"""Generate ``docs/CLI_REFERENCE.md`` from the Click command tree.

The hand-written reference drifted: 70 commands are registered and 14 of them were
never mentioned in it. A reference is the one kind of documentation that should never
be written by hand -- it is a projection of the code, so derive it and let a test fail
when the two disagree.

Usage::

    python scripts/generate_cli_reference.py            # write the file
    python scripts/generate_cli_reference.py --check    # exit 1 if it is out of date

``tests/test_cli_reference_is_current.py`` runs the same comparison, so a command added
without regenerating fails the build rather than silently going undocumented. This
mirrors ``scripts/sync_dev_skills.py`` and its drift test.

Explanatory material -- why ``validate-dbt-contracts`` differs from ``validate-dbt``,
what the machine-output contract guarantees -- deliberately does *not* live here. It is
in ``docs/design/cli-behaviour-notes.md``, because it is reasoning rather than surface,
and a generator would flatten it away on the next run.
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "docs" / "CLI_REFERENCE.md"
PROGRAM = "kairos-ontology"

_HEADER = """# CLI Reference

<!-- Generated by scripts/generate_cli_reference.py. Do not edit by hand. -->

Every command the CLI exposes, derived from the command tree itself so it cannot drift
from the code. Regenerate with:

```
python scripts/generate_cli_reference.py
```

`tests/test_cli_reference_is_current.py` fails if this file and the CLI disagree.

For *why* a command behaves as it does -- the machine-output contract, the three ERD
projections, `validate-dbt-contracts` versus `validate-dbt`, opt-in sample redaction --
see [CLI behaviour notes](design/cli-behaviour-notes.md). This file documents surface,
not reasoning.
"""


def _walk(command: click.Command, path: tuple[str, ...]) -> list[tuple[tuple[str, ...], click.Command]]:
    """Return ``(path, command)`` for every non-hidden command, depth-first by name."""
    found: list[tuple[tuple[str, ...], click.Command]] = []
    if path:
        found.append((path, command))
    if isinstance(command, click.Group):
        for name in sorted(command.commands):
            child = command.commands[name]
            if getattr(child, "hidden", False):
                continue
            found.extend(_walk(child, (*path, name)))
    return found


def _usage(command: click.Command, path: tuple[str, ...]) -> str:
    context = click.Context(command, info_name=f"{PROGRAM} {' '.join(path)}")
    pieces = command.collect_usage_pieces(context)
    return f"{PROGRAM} {' '.join(path)} {' '.join(pieces)}".rstrip()


def _option_rows(command: click.Command) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for param in command.params:
        if getattr(param, "hidden", False) or param.name == "help":
            continue
        if isinstance(param, click.Argument):
            continue
        flags = ", ".join(f"`{opt}`" for opt in (*param.opts, *param.secondary_opts))
        default = ""
        if param.required:
            default = "**required**"
        elif param.default not in (None, False, (), []):
            default = f"`{param.default}`"
        help_text = " ".join((param.help or "").split())
        rows.append((flags, default, help_text))
    return rows


def _argument_rows(command: click.Command) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for param in command.params:
        if not isinstance(param, click.Argument):
            continue
        arity = "required" if param.required else "optional"
        if param.nargs == -1:
            arity = "variadic"
        rows.append((f"`{param.name.upper()}`", arity))
    return rows


def _escape_cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(root: click.Group) -> str:
    commands = _walk(root, ())
    lines = [_HEADER, "", f"{len(commands)} commands.", "", "## Index", "", "| Command | Summary |", "|---|---|"]

    for path, command in commands:
        name = " ".join(path)
        anchor = "#" + name.replace(" ", "-").replace("_", "-")
        summary = _escape_cell(" ".join(command.get_short_help_str(limit=120).split()))
        lines.append(f"| [`{name}`]({anchor}) | {summary} |")

    for path, command in commands:
        name = " ".join(path)
        lines += ["", f"## {name}", ""]
        body = " ".join((command.help or command.get_short_help_str(limit=200) or "").split())
        if body:
            lines += [body, ""]
        lines += ["```", _usage(command, path), "```", ""]

        arguments = _argument_rows(command)
        if arguments:
            lines += ["| Argument | Arity |", "|---|---|"]
            lines += [f"| {cell} | {arity} |" for cell, arity in arguments]
            lines.append("")

        options = _option_rows(command)
        if options:
            lines += ["| Option | Default | Description |", "|---|---|---|"]
            lines += [
                f"| {flags} | {default} | {_escape_cell(help_text)} |"
                for flags, default, help_text in options
            ]
            lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    from kairos_ontology.cli.main import cli

    generated = render(cli)
    check = "--check" in sys.argv

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current == generated:
            print(f"{OUTPUT.relative_to(REPO).as_posix()} is current")
            return 0
        print(
            f"{OUTPUT.relative_to(REPO).as_posix()} is out of date -- "
            "run `python scripts/generate_cli_reference.py`",
            file=sys.stderr,
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(generated)
    print(f"wrote {OUTPUT.relative_to(REPO).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
