<# 
.SYNOPSIS
    Install git pre-commit hook that syncs .github/ → scaffold/ before each commit.

.DESCRIPTION
    Writes a pre-commit hook to .git/hooks/pre-commit. The hook runs the
    sync-dev-skills.py script and stages any changed scaffold files.
    
    Safe to run multiple times (idempotent).

.EXAMPLE
    .\scripts\install-hooks.ps1
#>

$RepoRoot = (git rev-parse --show-toplevel 2>$null)
if (-not $RepoRoot) {
    Write-Error "Not inside a git repository."
    exit 1
}

$HooksDir = Join-Path $RepoRoot ".git" "hooks"
$HookFile = Join-Path $HooksDir "pre-commit"

# Create hooks directory if it doesn't exist
if (-not (Test-Path $HooksDir)) {
    New-Item -ItemType Directory -Path $HooksDir -Force | Out-Null
}

$HookContent = @'
#!/bin/sh
# Auto-generated by scripts/install-hooks.ps1
# Syncs .github/ skills → scaffold/ before each commit

# Run the sync script
python scripts/sync_dev_skills.py
if [ $? -ne 0 ]; then
    echo "ERROR: sync-dev-skills.py failed"
    exit 1
fi

# Stage any scaffold changes produced by the sync
git add src/kairos_ontology/scaffold/skills/ src/kairos_ontology/scaffold/copilot-instructions.md 2>/dev/null

exit 0
'@

Set-Content -Path $HookFile -Value $HookContent -Encoding UTF8 -NoNewline

Write-Host "✅ Pre-commit hook installed at: $HookFile"
Write-Host "   The hook syncs .github/ → scaffold/ on every commit."
