<# 
.SYNOPSIS
    Install git pre-commit hook that syncs .claude/ → scaffold/ before each commit.

.DESCRIPTION
    Writes a pre-commit hook to .git/hooks/pre-commit. The hook runs the
    sync-dev-skills.py script and stages any changed scaffold files.
    
    Safe to run multiple times (idempotent).

.EXAMPLE
    .\scripts\install-hooks.ps1
#>

$RepoRoot = (git rev-parse --show-toplevel 2>$null)
if (-not $RepoRoot) {
    Write-Error "Not inside a git repository."
    exit 1
}

$HooksDir = Join-Path $RepoRoot ".git" "hooks"
$HookFile = Join-Path $HooksDir "pre-commit"

# Create hooks directory if it doesn't exist
if (-not (Test-Path $HooksDir)) {
    New-Item -ItemType Directory -Path $HooksDir -Force | Out-Null
}

$HookContent = @'
#!/bin/sh
# Auto-generated by scripts/install-hooks.ps1
# Syncs .claude/ skills → scaffold/ before each commit

# Run the sync script
python scripts/sync_dev_skills.py
if [ $? -ne 0 ]; then
    echo "ERROR: sync-dev-skills.py failed"
    exit 1
fi

# Stage any scaffold changes produced by the sync
git add src/kairos_ontology/scaffold/skills/ src/kairos_ontology/scaffold/copilot-instructions.md 2>/dev/null

exit 0
'@

Set-Content -Path $HookFile -Value $HookContent -Encoding UTF8 -NoNewline

# --- Pre-push hook: block large files from being pushed ---
$PrePushFile = Join-Path $HooksDir "pre-push"

$PrePushContent = @'
#!/bin/sh
# Auto-generated by scripts/install-hooks.ps1
# Rejects files larger than 10 MB in the push payload

MAX_BYTES=$((10 * 1024 * 1024))

while read -r _local_ref _local_sha _remote_ref _remote_sha; do
    if [ "$_local_sha" = "0000000000000000000000000000000000000000" ]; then
        continue
    fi
    for file in $(git diff --name-only $remote_sha $local_sha 2>/dev/null || git ls-files); do
        if [ -f "$file" ]; then
            size=$(git cat-file -s "$local_sha:$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || echo 0)
            if [ "$size" -gt "$MAX_BYTES" ]; then
                echo "ERROR: $file is $((size / 1024 / 1024)) MB (limit: 10 MB)"
                echo "       Add large files to .gitignore or use Git LFS."
                exit 1
            fi
        fi
    done
done

exit 0
'@

Set-Content -Path $PrePushFile -Value $PrePushContent -Encoding UTF8 -NoNewline

Write-Host "✅ Pre-commit hook installed at: $HookFile"
Write-Host "   The hook syncs .claude/ → scaffold/ on every commit."
Write-Host "✅ Pre-push hook installed at: $PrePushFile"
Write-Host "   The hook blocks files larger than 10 MB from being pushed."
